const { chromium, expect } = require('../go-admin-ui/node_modules/@playwright/test');
const fs=require('fs'),path=require('path');const rt=path.resolve(__dirname,'../../runtime/t6');
(async()=>{
 const browser=await chromium.launch({executablePath:'/Users/lostar/Library/Caches/ms-playwright/chromium-1228/chrome-mac-arm64/Google Chrome for Testing.app/Contents/MacOS/Google Chrome for Testing',headless:true});
 const page=await browser.newPage({viewport:{width:1440,height:1100}});const checks=[],errors=[];let authorization;const url='http://127.0.0.1:19529';const api='http://127.0.0.1:18097/api/v1';
 page.on('pageerror',e=>errors.push(e.message));page.on('request',r=>{if(r.url().startsWith(api)&&r.headers().authorization)authorization=r.headers().authorization});
 await page.route('**/*',r=>{const u=new URL(r.request().url());return ['127.0.0.1','localhost'].includes(u.hostname)||['data:','blob:'].includes(u.protocol)?r.continue():r.abort()});
 const check=(name,v=true)=>{console.log(name,v?'PASS':'FAIL');checks.push({name,status:v?'PASS':'FAIL',time:new Date().toISOString()});if(!v)throw Error(name)};
 const settle=()=>page.waitForLoadState('networkidle');
 const put=async(testid,fragment)=>{const wait=page.waitForResponse(r=>r.url().includes(fragment)&&r.request().method()==='PUT');await page.getByTestId(testid).click();const r=await(await wait).json();check(testid+' succeeds',r.code===200);await settle()};
 const select=async(el,text)=>{
  await el.scrollIntoViewIfNeeded();await el.click();
  const dropdown=page.locator('.el-select-dropdown:visible');await dropdown.getByText(text,{exact:true}).waitFor({state:'visible'});
  // Native keyboard selection avoids the portal repositioning/scroll race in long forms.
  for(let n=0;n<110;n++){await page.keyboard.press('ArrowDown');const hovered=dropdown.locator('.is-hovering');if(await hovered.count()&&await hovered.first().innerText()===text){await page.keyboard.press('Enter');await expect(dropdown).toBeHidden();return}}
  throw Error('Option not reachable by keyboard: '+text);
 };
 const batchData=async(id)=>(await(await page.request.get(api+'/passport-batches/'+id,{headers:{Authorization:authorization}})).json()).data;
 const idFrom=()=>new URLSearchParams(page.url().split('?')[1]).get('batch');
 const code='PF-T6-BROWSER-'+Date.now();let pid,a,b,c;
 try{
 await page.goto(url+'/#/login',{waitUntil:'networkidle'});const cred=JSON.parse(fs.readFileSync(rt+'/credentials.json'));await page.locator('input[name=username]').fill(cred.admin_username);await page.locator('input[name=password]').fill(cred.admin_password);for(const el of await page.locator('input').all()){const n=await el.getAttribute('name');if(!['username','password'].includes(n)&&await el.isVisible())await el.fill('0')};await page.locator('button.submit-btn').click();await page.waitForURL(u=>u.hash.includes('/dashboard'));await settle();check('Browser login');
 await page.getByText('产品数字身份证',{exact:true}).click();await page.getByRole('menuitem',{name:'产品模板',exact:true}).click();await page.getByTestId('create-product').click();await page.getByTestId('new-code').fill(code);await page.getByTestId('new-name').fill('T6 Browser — TEST RECORD — NOT FOR COMMERCIAL USE');await page.getByTestId('confirm-create').click();await page.getByTestId('selected-revision').waitFor();await settle();pid=new URLSearchParams(page.url().split('?')[1]).get('product');check('T5 Product created through browser');
 await page.getByTestId('package_quantity').fill('25');await put('save-content','/revisions/');await page.getByTestId('translation-approved').click();await put('save-translation','/translations');await page.getByTestId('seal-revision').click();await page.locator('.el-message-box__btns .el-button--primary').click();await expect(page.getByTestId('selected-revision')).toContainText('已封版');await page.getByTestId('set-default').click();await expect(page.getByTestId('set-default')).toBeDisabled();await settle();check('R1 sealed default in UI');
 await page.getByTestId('clone-revision').click();await expect(page.getByTestId('selected-revision')).toContainText('R2');await page.getByTestId('package_quantity').fill('30');await put('save-content','/revisions/');await page.getByTestId('translation-approved').click();await put('save-translation','/translations');await page.getByTestId('seal-revision').click();await page.locator('.el-message-box__btns .el-button--primary').click();await expect(page.getByTestId('selected-revision')).toContainText('已封版');check('R2 sealed without implicit default change');
 await page.getByRole('menuitem',{name:'批次身份证',exact:true}).click();await page.getByTestId('create-batch').waitFor();check('Batch menu and list');
 const create=async(suffix,expected)=>{await page.getByTestId('create-batch').click();await select(page.getByTestId('new-batch-product'),code);await expect(page.getByTestId('new-batch-base')).toContainText('R'+expected);check('Create dialog displays R'+expected);await page.getByTestId('new-batch-code').fill(code+'-'+suffix);await page.getByTestId('confirm-batch-create').click();await expect(page.getByTestId('batch-heading')).toContainText(code+'-'+suffix);await settle();check('Batch '+suffix+' binds R'+expected,(await page.getByTestId('batch-base').innerText()).includes('R'+expected));return idFrom()};
 a=await create('A',1);await expect(page.getByTestId('effective-package_quantity')).toContainText('25');check('Effective inherited25');
 await page.getByTestId('batch-note').fill('T6 changed facts — TEST RECORD — NOT FOR COMMERCIAL USE');
 const ov=page.getByTestId('override-package_quantity');await ov.getByText('覆盖',{exact:true}).click();await ov.locator('input:not([type=radio])').fill('20');await put('save-batch','/passport-batches/');await expect(page.getByTestId('effective-package_quantity')).toContainText('20');await expect(page.getByTestId('effective-package_quantity')).toContainText('来自批次覆盖');check('Override20 effective source');
 await ov.getByText('主动清空',{exact:true}).click();await put('save-batch','/passport-batches/');await expect(page.getByTestId('effective-package_quantity')).toContainText('已主动清空');check('Clear rendered');
 await ov.getByText('恢复继承',{exact:true}).click();await put('save-batch','/passport-batches/');await expect(page.getByTestId('effective-package_quantity')).toContainText('25');check('Reset restored inherit');
 for(const [i,name] of ['MOISTURE','BULK_DENSITY','BLACK_SPECKS','APPEARANCE'].entries()){
  await page.getByTestId('add-inspection').click();const card=page.getByTestId('inspection-'+i);await card.getByTestId('item_code').fill(name);await card.getByTestId('name').fill(name+' TEST');
  if(i===3){await select(card.getByTestId('value_type'),'文本');await card.getByTestId('text_value').fill('Off-white flakes')}else{await card.getByTestId('numeric_value').fill('6.8')}
  await select(card.getByTestId('judgement'),'通过');await card.getByTestId('unit').fill(i===3?'description':'%');await card.getByTestId('specification').fill('T6 test specification');
 }
 await put('save-batch','/passport-batches/');await page.reload({waitUntil:'networkidle'});await page.getByTestId('inspection-3').waitFor();check('Four dynamic items survive reload',await page.locator('.inspection').count()===4);check('Numeric persisted',await page.getByTestId('inspection-0').getByTestId('numeric_value').inputValue()==='6.8');check('Text persisted',await page.getByTestId('inspection-3').getByTestId('text_value').inputValue()==='Off-white flakes');
 await page.getByTestId('batch-note').fill('UNSAVED');await page.getByRole('menuitem',{name:'产品模板',exact:true}).click();await page.locator('.el-message-box').waitFor();await page.locator('.el-message-box__btns .el-button').first().click();check('Unsaved navigation cancellation retains page',await page.getByTestId('batch-heading').isVisible());await put('save-batch','/passport-batches/');
 await page.getByRole('menuitem',{name:'产品模板',exact:true}).click();await settle();await page.goto(url+'/#/passport/products?product='+pid,{waitUntil:'networkidle'});await page.reload({waitUntil:'networkidle'});await page.getByTestId('view-r2').click();await page.getByTestId('set-default').click();await expect(page.getByTestId('set-default')).toBeDisabled();await settle();check('Default switched to R2 through UI');
 await page.goto(url+'/#/passport/batches?batch='+a,{waitUntil:'networkidle'});await expect(page.getByTestId('batch-base')).toContainText('R1');await expect(page.getByTestId('effective-package_quantity')).toContainText('25');check('Old batch stays R1 after default switch');
 await page.getByText('返回列表',{exact:true}).click();await page.getByTestId('create-batch').waitFor();b=await create('B',2);await expect(page.getByTestId('effective-package_quantity')).toContainText('30');check('New batch inherits R2 quantity30');
 await page.goto(url+'/#/passport/batches?batch='+a,{waitUntil:'networkidle'});const ov2=page.getByTestId('override-package_quantity');await ov2.getByText('覆盖',{exact:true}).click();await ov2.locator('input:not([type=radio])').fill('20');await put('save-batch','/passport-batches/');await page.getByTestId('clone-batch').click();await page.getByTestId('new-batch-code').fill(code+'-CLONE');await page.getByTestId('confirm-batch-create').click();await expect(page.getByTestId('batch-heading')).toContainText('-CLONE');await settle();c=idFrom();const cv=await batchData(c);check('Clone keeps R1 and override20',cv.base.revision_number===1&&cv.effective.find(f=>f.field_key==='package_quantity').value==='20');check('Clone copies four item definitions',cv.inspections.length===4);check('Clone clears actual results and judgement',cv.inspections.every(i=>i.numeric_value===null&&i.text_value===null&&i.judgement==='not_tested'&&i.tested_on===null));check('Clone clears batch dates',cv.batch.production_date===null&&cv.batch.expiry_date===null);
 await page.getByTestId('inspection-0').getByTestId('numeric_value').fill('7.2');await select(page.getByTestId('inspection-0').getByTestId('judgement'),'通过');await put('save-batch','/passport-batches/');await page.reload({waitUntil:'networkidle'});check('Clone new measured result persists',await page.getByTestId('inspection-0').getByTestId('numeric_value').inputValue()==='7.2');
 await page.screenshot({path:rt+'/test-artifacts/browser-detail.png',fullPage:true});await page.setViewportSize({width:1280,height:900});check('1280 detail no document overflow',await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await page.screenshot({path:rt+'/test-artifacts/browser-1280.png'});await page.getByText('返回列表',{exact:true}).click();await settle();check('1280 list no document overflow',await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await page.screenshot({path:rt+'/test-artifacts/browser-list.png'});check('No uncaught JavaScript errors',errors.length===0);
 fs.writeFileSync(rt+'/test-artifacts/browser-fixtures.json',JSON.stringify({product:pid,a,b,c,detail:await batchData(c)},null,2));
 }catch(e){checks.push({name:'Browser completion',status:'FAIL',error:e.message+' URL='+page.url()});await page.screenshot({path:rt+'/test-artifacts/browser-failure.png',fullPage:true});process.exitCode=1}
 finally{fs.writeFileSync(rt+'/test-artifacts/browser-tests.json',JSON.stringify({checks,errors},null,2));console.log(checks);await browser.close()}
})();
