const {chromium,expect}=require('../go-admin-ui/node_modules/@playwright/test');
const fs=require('fs'),path=require('path');const rt=path.resolve(__dirname,'../../runtime/t8');
(async()=>{const fresh=process.argv.includes('fresh');const cred=JSON.parse(fs.readFileSync(rt+'/credentials.json'));const users=JSON.parse(fs.readFileSync(rt+'/test-artifacts/'+(fresh?'fresh-users':'users')+'.json'));const checks=[],errors=[];const url='http://127.0.0.1:'+(fresh?'19533':'19532'),api='http://127.0.0.1:'+(fresh?'18102':'18101')+'/api/v1';const browser=await chromium.launch({executablePath:'/Users/lostar/Library/Caches/ms-playwright/chromium-1228/chrome-mac-arm64/Google Chrome for Testing.app/Contents/MacOS/Google Chrome for Testing',headless:true});let page,ctx,authorization,bid,pid;
const check=(name,value=true)=>{checks.push({name,status:value?'PASS':'FAIL'});console.log(name,value);if(!value)throw Error(name)};
const settle=()=>page.waitForLoadState('networkidle');
async function login(role){if(ctx)await ctx.close();ctx=await browser.newContext({locale:'zh-CN',viewport:{width:1440,height:1100}});page=await ctx.newPage();page.setDefaultTimeout(15000);page.on('pageerror',e=>errors.push(e.message));page.on('request',r=>{if(r.url().startsWith(api)&&r.headers().authorization)authorization=r.headers().authorization});await page.route('**/*',r=>{const u=new URL(r.request().url());return ['127.0.0.1','localhost'].includes(u.hostname)||['data:','blob:'].includes(u.protocol)?r.continue():r.abort()});await page.goto(url+'/#/login',{waitUntil:'networkidle'});await page.locator('input[name=username]').fill(users[role].username);await page.locator('input[name=password]').fill(cred.test_password);for(const el of await page.locator('input').all()){const n=await el.getAttribute('name');if(!['username','password'].includes(n)&&await el.isVisible())await el.fill('0')};await page.locator('button.submit-btn').click();await page.waitForURL(u=>u.hash.includes('/dashboard'));await settle();check('Browser '+role+' login')}
async function read(p){return(await(await page.request.get(api+'/'+p,{headers:{Authorization:authorization}})).json()).data}
async function select(el,text){await el.scrollIntoViewIfNeeded();await el.click();const dd=page.locator('.el-select-dropdown:visible');await dd.getByText(text,{exact:true}).waitFor();for(let i=0;i<110;i++){await page.keyboard.press('ArrowDown');const h=dd.locator('.is-hovering');if(await h.count()&&await h.first().innerText()===text){await page.keyboard.press('Enter');return}}throw Error('select '+text)}
async function review(action,reason='',success=true){await page.getByTestId('review-'+action).click();if(reason)await page.getByTestId('review-reason').fill(reason);const promise=page.waitForResponse(r=>r.url().endsWith('/review/'+action)&&r.request().method()==='POST');await page.getByTestId('review-confirm').click();const result=await(await promise).json();check('Browser '+action+(success?'':' self denied'),result.code===(success?200:403));if(success)await expect(page.getByTestId('review-confirm')).toBeHidden();await settle()}
try{
 await login('editor');await page.goto(url+'/#/passport/products');await page.getByTestId('create-product').click();const code='PF-T8-UI-'+Date.now();await page.getByTestId('new-code').fill(code);await page.getByTestId('new-name').fill('T8 BROWSER TEST ONLY');await page.getByTestId('confirm-create').click();await page.getByTestId('selected-revision').waitFor();await settle();pid=new URLSearchParams(page.url().split('?')[1]).get('product');check('Browser Editor creates Product');await page.getByTestId('translation-approved').click();await page.getByTestId('save-translation').click();await settle();await page.getByTestId('seal-revision').click();await page.locator('.el-message-box__btns .el-button--primary').click();await settle();await page.getByTestId('set-default').click();await settle();check('Browser seal and set default');
 await page.goto(url+'/#/passport/batches');await page.getByTestId('create-batch').click();await select(page.getByTestId('new-batch-product'),code);await expect(page.getByTestId('new-batch-base')).toContainText('R1');await page.getByTestId('new-batch-code').fill('BT-T8-UI-'+Date.now());for(const [label,value] of [['生产日期','2026-09-09'],['有效期','2027-09-09']]){const input=page.locator('.el-dialog:visible .el-form-item').filter({has:page.locator('label',{hasText:label})}).locator('input');await input.fill(value);await input.press('Enter')};await page.getByTestId('confirm-batch-create').click();await page.getByTestId('batch-heading').waitFor();await settle();bid=new URLSearchParams(page.url().split('?')[1]).get('batch');check('Browser Editor creates Batch');
 await page.getByTestId('section-add').click();await page.getByTestId('section-key').fill('browser_review');await page.getByTestId('section-title').fill('T8 browser section');await page.getByTestId('section-text').fill('T8 frozen browser content');await page.getByTestId('section-save').click();await expect(page.getByTestId('section-editor')).toBeHidden();await settle();check('Browser custom module');
 await page.getByTestId('batch-note').fill('T8 pending unsaved');await expect(page.getByTestId('review-submit')).toBeDisabled();check('Unsaved changes block submission');await page.getByTestId('save-batch').click();await settle();await review('submit');await expect(page.getByTestId('review-state')).toContainText('待审核');await expect(page.getByTestId('batch-note')).toBeDisabled();check('Pending form locked');await page.screenshot({path:rt+'/test-artifacts/'+(fresh?'fresh-':'')+'browser-pending.png',fullPage:true});
 await login('viewer');await page.goto(url+'/#/passport/batches?batch='+bid);await page.getByTestId('review-state').waitFor();await expect(page.getByTestId('batch-note')).toBeDisabled();await expect(page.getByTestId('review-approve')).toHaveCount(0);await expect(page.getByTestId('save-batch')).toHaveCount(0);check('Viewer readonly browser');
 await login('reviewer');await page.goto(url+'/#/passport/reviews');await page.getByText('BT-T8-UI-', {exact:false}).first().waitFor();check('Reviewer actual queue');await page.goto(url+'/#/passport/reviews?batch='+bid);await page.getByTestId('review-state').waitFor();await expect(page.getByTestId('review-panel')).toContainText('T8 frozen browser content');check('Frozen custom preview visible');await review('reject','T8 browser: clarify note');await expect(page.getByTestId('review-state')).toContainText('草稿');
 await login('editor');await page.goto(url+'/#/passport/batches?batch='+bid);await page.getByTestId('review-state').waitFor();await expect(page.getByTestId('batch-note')).toBeEnabled();await expect(page.getByTestId('review-history')).toContainText('T8 browser: clarify note');await page.getByTestId('batch-note').fill('T8 corrected browser note');await page.getByTestId('save-batch').click();await settle();await review('submit');check('Browser reject edit resubmit');
 await login('reviewer');await page.goto(url+'/#/passport/reviews?batch='+bid);await page.getByTestId('review-state').waitFor();await expect(page.getByTestId('review-panel')).toContainText('T8 corrected browser note');await review('approve');await expect(page.getByTestId('review-state')).toContainText('待发布（未发布）');check('Browser approved not published');await expect(page.getByTestId('review-history').locator('.el-table__body tr')).toHaveCount(2);await page.setViewportSize({width:1280,height:900});check('No document horizontal overflow',await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth));await page.screenshot({path:rt+'/test-artifacts/'+(fresh?'fresh-':'')+'browser-approved.png',fullPage:true});
 await login('editor_reviewer');const fixtures=JSON.parse(fs.readFileSync(rt+'/test-artifacts/'+(fresh?'fresh-api-fixtures':'api-fixtures')+'.json'));await page.goto(url+'/#/passport/reviews?batch='+fixtures.self_batch_id);await page.getByTestId('review-state').waitFor();await review('approve','',false);check('Composite self approval rejected through browser');check('No browser exceptions',errors.length===0);
 fs.writeFileSync(rt+'/test-artifacts/'+(fresh?'fresh-':'')+'browser-fixtures.json',JSON.stringify({pid,bid}));
}catch(e){console.error(e);checks.push({name:'Browser completed',status:'FAIL',error:e.message});if(page)await page.screenshot({path:rt+'/test-artifacts/'+(fresh?'fresh-':'')+'browser-failure.png',fullPage:true});process.exitCode=1}finally{fs.writeFileSync(rt+'/test-artifacts/'+(fresh?'fresh-':'')+'browser-tests.json',JSON.stringify({checks,errors},null,2));await browser.close()}
})();
