const { chromium, expect } = require('../go-admin-ui/node_modules/@playwright/test');
const fs=require('fs'),path=require('path');const rt=path.resolve(__dirname,'../../runtime/t7');
(async()=>{
const browser=await chromium.launch({executablePath:'/Users/lostar/Library/Caches/ms-playwright/chromium-1228/chrome-mac-arm64/Google Chrome for Testing.app/Contents/MacOS/Google Chrome for Testing',headless:true});
const page=await browser.newPage({viewport:{width:1440,height:1100},locale:'zh-CN'});const checks=[],errors=[],dialogs=[];let authorization;const url='http://127.0.0.1:19530',api='http://127.0.0.1:18099/api/v1';
page.on('pageerror',e=>errors.push(e.message));page.on('dialog',async d=>{dialogs.push(d.message());await d.dismiss()});page.on('request',r=>{if(r.url().startsWith(api)&&r.headers().authorization)authorization=r.headers().authorization});
await page.route('**/*',r=>{const u=new URL(r.request().url());return ['127.0.0.1','localhost'].includes(u.hostname)||['data:','blob:'].includes(u.protocol)?r.continue():r.abort()});
const check=(name,v=true)=>{console.log(name,v?'PASS':'FAIL');checks.push({name,status:v?'PASS':'FAIL'});if(!v)throw Error(name)};
const settle=()=>page.waitForLoadState('networkidle');const manager=()=>page.getByTestId('section-manager');const editor=()=>page.getByTestId('section-editor');
const select=async(el,text)=>{await el.scrollIntoViewIfNeeded();await el.click();const dd=page.locator('.el-select-dropdown:visible');await dd.getByText(text,{exact:true}).waitFor();for(let n=0;n<110;n++){await page.keyboard.press('ArrowDown');const h=dd.locator('.is-hovering');if(await h.count()&&await h.first().innerText()===text){await page.keyboard.press('Enter');await expect(dd).toBeHidden();return}}throw Error('option '+text)};
const read=async(p)=>(await(await page.request.get(api+'/'+p,{headers:{Authorization:authorization}})).json()).data;
const saveSection=async(success=true)=>{const pending=page.waitForResponse(r=>r.url().includes('/sections')&&['POST','PUT'].includes(r.request().method()));await page.getByTestId('section-save').click();const x=await(await pending).json();check(success?'Section save':'XSS rejected in browser',success?x.code===200:x.code===422);if(success)await expect(editor()).toBeHidden();await settle()};
const menu=async(key,action)=>{const row=page.getByTestId('section-row-'+key);await row.getByText('更多',{exact:true}).click();await page.getByRole('menuitem',{name:action,exact:true}).click();await settle()};
const code='PF-T7-BROWSER-'+Date.now();let pid,rid,bid,cid;
try{
await page.goto(url+'/#/login',{waitUntil:'networkidle'});const cred=JSON.parse(fs.readFileSync(rt+'/credentials.json'));await page.locator('input[name=username]').fill(cred.admin_username);await page.locator('input[name=password]').fill(cred.admin_password);for(const el of await page.locator('input').all()){const n=await el.getAttribute('name');if(!['username','password'].includes(n)&&await el.isVisible())await el.fill('0')};await page.locator('button.submit-btn').click();await page.waitForURL(u=>u.hash.includes('/dashboard'));await settle();check('Browser login');
await page.getByText('产品数字身份证',{exact:true}).click();await page.getByRole('menuitem',{name:'产品模板',exact:true}).click();await page.getByTestId('create-product').click();await page.getByTestId('new-code').fill(code);await page.getByTestId('new-name').fill('T7 Browser TEST RECORD — NOT FOR COMMERCIAL USE');await page.getByTestId('confirm-create').click();await page.getByTestId('selected-revision').waitFor();await settle();pid=new URLSearchParams(page.url().split('?')[1]).get('product');rid=(await read('passport-products/'+pid)).revisions[0].id;check('Create product draft in browser');
for(const kind of ['text','key_value','table']){
 await manager().getByTestId('section-add').click();await page.getByTestId('section-key').fill('browser_'+kind);if(kind!=='text')await select(page.getByTestId('section-type'),kind);await page.getByTestId('section-title').fill('TEST '+kind);
 if(kind==='text'){
  await page.getByTestId('section-allow-hide').click();await page.getByTestId('section-text').fill('<script>alert(1)</script>');await saveSection(false);check('No injected browser script',dialogs.length===0);await page.getByTestId('section-text').fill('TEST EN statement');
  for(const lang of ['zh-CN','ar']){await page.locator('.el-dialog').getByRole('tab',{name:lang,exact:true}).click();await page.getByText('添加此语言',{exact:true}).click();await page.getByTestId('section-title').fill('TEST '+lang);await page.getByTestId('section-text').fill(lang==='ar'?'اختبار':'测试说明');if(lang==='ar')check('Arabic editor RTL',await page.getByTestId('section-translation').getAttribute('dir')==='rtl')}
 }else if(kind==='key_value'){
  await page.getByText('添加条目',{exact:true}).click();await editor().getByPlaceholder('标签',{exact:true}).fill('TEST source');await editor().getByPlaceholder('值',{exact:true}).fill('TEST lot');
 }else{
  await editor().getByPlaceholder('标签',{exact:true}).fill('TEST result');await page.getByText('添加行',{exact:true}).click();await editor().getByPlaceholder('TEST result',{exact:true}).fill('TEST pass');
 }
 await saveSection();await expect(page.getByTestId('section-row-browser_'+kind)).toBeVisible();check('Structured '+kind+' builder');
}
await menu('browser_table','上移');check('Reorder through UI',(await read(`passport-products/${pid}/revisions/${rid}/sections`)).sections[0].section_key==='browser_table');
await page.getByTestId('translation-approved').click();await page.getByTestId('save-translation').click();await settle();await page.getByTestId('seal-revision').click();await page.locator('.el-message-box__btns .el-button--primary').click();await expect(page.getByTestId('selected-revision')).toContainText('已封版');await expect(manager().getByTestId('section-add')).toBeDisabled();check('Sealed module UI read-only');await page.getByTestId('set-default').click();await expect(page.getByTestId('set-default')).toBeDisabled();
await page.getByTestId('clone-revision').click();await expect(page.getByTestId('selected-revision')).toContainText('R2');await settle();await expect(manager().locator('.section-row')).toHaveCount(3);check('Revision clone copies three modules');await expect(manager().getByTestId('section-add')).toBeEnabled();
await page.getByRole('menuitem',{name:'批次身份证',exact:true}).click();await page.getByTestId('create-batch').click();await select(page.getByTestId('new-batch-product'),code);await page.getByTestId('new-batch-code').fill(code+'-A');await page.getByTestId('confirm-batch-create').click();await page.getByTestId('batch-heading').waitFor();await settle();bid=new URLSearchParams(page.url().split('?')[1]).get('batch');await expect(page.getByTestId('section-row-browser_text')).toContainText('继承');check('Batch inherited modules in UI');
await page.getByTestId('section-row-browser_text').getByText('覆盖',{exact:true}).click();await page.getByTestId('section-text').fill('TEST batch override');await saveSection();await expect(page.getByTestId('section-row-browser_text')).toContainText('已覆盖');check('Batch override UI');
await menu('browser_text','隐藏');await expect(page.getByTestId('section-row-browser_text')).toContainText('已隐藏');check('Hidden has no original content',!(await page.getByTestId('section-row-browser_text').innerText()).includes('TEST EN statement'));
await menu('browser_text','恢复继承');await page.locator('.el-message-box__btns .el-button--primary').click();await settle();await expect(page.getByTestId('section-row-browser_text')).toContainText('继承');check('Reset restores inherited UI');
await manager().getByTestId('section-add').click();await page.getByTestId('section-key').fill('customer_requirement');await page.getByTestId('section-title').fill('TEST customer');await page.getByTestId('section-text').fill('TEST PRIVATE customer requirements');await saveSection();await expect(page.getByTestId('section-row-customer_requirement')).toContainText('批次独有');check('Batch-only builder');
await page.getByTestId('section-row-browser_table').getByText('覆盖',{exact:true}).click();await saveSection();
await page.reload({waitUntil:'networkidle'});await page.getByTestId('section-row-customer_requirement').waitFor();check('Sections persist after refresh');await page.getByTestId('clone-batch').click();await page.getByTestId('new-batch-code').fill(code+'-CLONE');await page.getByTestId('confirm-batch-create').click();await expect(page.getByTestId('batch-heading')).toContainText('-CLONE');await settle();cid=new URLSearchParams(page.url().split('?')[1]).get('batch');const source=await read('passport-batches/'+bid+'/sections'),clone=await read('passport-batches/'+cid+'/sections');check('Batch clone local sections new IDs',clone.sections.length===2&&clone.sections.every(x=>!source.sections.some(y=>y.id===x.id)));
await page.screenshot({path:rt+'/test-artifacts/browser-detail.png',fullPage:true});await page.setViewportSize({width:1280,height:900});check('1280 no horizontal overflow',await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await page.screenshot({path:rt+'/test-artifacts/browser-1280.png'});check('No uncaught JS error',errors.length===0);check('No XSS dialog',dialogs.length===0);
fs.writeFileSync(rt+'/test-artifacts/browser-fixtures.json',JSON.stringify({pid,rid,bid,cid},null,2));
}catch(e){checks.push({name:'Browser completion',status:'FAIL',error:e.message+' URL='+page.url()});console.error(e);await page.screenshot({path:rt+'/test-artifacts/browser-failure.png',fullPage:true});process.exitCode=1}
finally{fs.writeFileSync(rt+'/test-artifacts/browser-tests.json',JSON.stringify({checks,errors,dialogs},null,2));await browser.close()}
})();
