const {chromium,expect}=require('../go-admin-ui/node_modules/@playwright/test');
const fs=require('fs'),path=require('path');const rt=path.resolve(__dirname,'../../runtime/t10');
(async()=>{const fresh=process.argv.includes('fresh');const cred=JSON.parse(fs.readFileSync(rt+'/credentials.json'));const users=JSON.parse(fs.readFileSync(rt+'/test-artifacts/'+(fresh?'fresh-users':'users')+'.json'));const checks=[],errors=[];const url='http://127.0.0.1:'+'19536',api='http://127.0.0.1:'+'18105'+'/api/v1';const browser=await chromium.launch({executablePath:'/Users/lostar/Library/Caches/ms-playwright/chromium-1228/chrome-mac-arm64/Google Chrome for Testing.app/Contents/MacOS/Google Chrome for Testing',headless:true});let page,ctx,authorization,bid,pid; const f=JSON.parse(fs.readFileSync(rt+'/test-artifacts/history-fixtures.json'));bid=f.browser.batch_id;const vs=f.browser.versions;const recovery=process.argv.includes('recovery');const smoke=process.argv.includes('smoke');
const check=(name,value=true)=>{checks.push({name,status:value?'PASS':'FAIL'});console.log(name,value);if(!value)throw Error(name)};
const settle=()=>page.waitForLoadState('networkidle');
async function login(role){if(ctx){await page.locator('.avatar-wrapper').hover();await page.getByText('退出登录',{exact:true}).click();await page.locator('.el-message-box__btns .el-button--primary').click();await page.waitForURL(u=>u.hash.includes('/login'));check('Browser actual logout');await ctx.close();}ctx=await browser.newContext({locale:'zh-CN',viewport:{width:1440,height:1100}});page=await ctx.newPage();page.setDefaultTimeout(15000);page.on('console',m=>{if(m.type()==='error'&&!m.text().includes('Failed to load resource')){errors.push(m.text());console.log('CONSOLE',m.text())}});page.on('pageerror',e=>errors.push(e.message));page.on('response',async r=>{if(r.url().includes('/publication/')){try{const d=await r.json();console.log('API',r.url(),d.code,d.msg)}catch{}}});page.on('request',r=>{if(r.url().startsWith(api)&&r.headers().authorization)authorization=r.headers().authorization});await page.route('**/*',r=>{const u=new URL(r.request().url());return ['127.0.0.1','localhost'].includes(u.hostname)||['data:','blob:'].includes(u.protocol)?r.continue():r.abort()});await page.goto(url+'/#/login',{waitUntil:'networkidle'});await page.locator('input[name=username]').fill(role==='admin'?cred.admin_username:users[role].username);await page.locator('input[name=password]').fill(role==='admin'?cred.admin_password:cred.test_password);for(const el of await page.locator('input').all()){const n=await el.getAttribute('name');if(!['username','password'].includes(n)&&await el.isVisible())await el.fill('0')};await page.locator('button.submit-btn').click();await page.waitForURL(u=>u.hash.includes('/dashboard'));await settle();check('Browser '+role+' login')}
async function read(p){return(await(await page.request.get(api+'/'+p,{headers:{Authorization:authorization}})).json()).data}
async function select(el,text){await el.scrollIntoViewIfNeeded();await el.click();const dd=page.locator('.el-select-dropdown:visible');await dd.getByText(text,{exact:true}).waitFor();for(let i=0;i<110;i++){await page.keyboard.press('ArrowDown');const h=dd.locator('.is-hovering');if(await h.count()&&await h.first().innerText()===text){await page.keyboard.press('Enter');return}}throw Error('select '+text)}
async function review(action,reason='',success=true){await page.getByTestId('review-'+action).click();if(reason)await page.getByTestId('review-reason').fill(reason);const promise=page.waitForResponse(r=>r.url().endsWith('/review/'+action)&&r.request().method()==='POST');await page.getByTestId('review-confirm').click();const result=await(await promise).json();if(result.code!==(success?200:403)) console.log('review response',result.code,result.msg);check('Browser '+action+(success?'':' self denied'),result.code===(success?200:403));if(success)await expect(page.getByTestId('review-confirm')).toBeHidden();await settle()}
const fixture=(action)=>{const p=require('child_process').spawnSync('python3',[path.join(__dirname,'browser_fixture.py'),action,bid],{encoding:'utf8'});if(p.status!==0)throw Error('fixture '+action+': '+p.stderr);return JSON.parse(p.stdout)};
async function goBatch(){await page.goto(url+'/#/passport/batches?batch='+bid);await page.reload();await page.getByTestId('review-state').waitFor();await settle()}
async function doPublish(expected){await page.getByTestId('publish-open').click();await page.evaluate(()=>{window.__t9PublishingSeen=false;new MutationObserver(()=>{if(document.querySelector('[data-testid="publishing-state"]'))window.__t9PublishingSeen=true}).observe(document.body,{subtree:true,childList:true})});const response=page.waitForResponse(r=>r.url().endsWith('/publication')&&r.request().method()==='POST');await page.getByTestId('publish-confirm').click();const result=await(await response).json();check('Browser publish result '+expected,result.code===200&&result.data.record.publish_status===expected);await expect(page.getByTestId('publish-confirm')).toBeHidden();await settle();check('Browser displayed Publishing',await page.evaluate(()=>window.__t9PublishingSeen));return result.data}
try{
 if(smoke){ await login('admin');await goBatch();await expect(page.getByTestId('history-health')).toContainText('一致');await expect(page.getByTestId('published-current')).toContainText('V5');await page.getByTestId('version-detail-1').click();await expect(page.getByTestId('version-integrity')).toContainText('验证通过');await page.locator('.el-dialog:visible .el-dialog__headerbtn').click();check('Final history UI with current/file versions and read-only detail'); }else if(!recovery){
 for(const role of ['viewer','editor','reviewer']){
  await login(role);await goBatch();await expect(page.getByTestId('version-history')).toContainText('V1');await expect(page.getByTestId('rollback-1')).toHaveCount(0);check(role+' reads complete history, rollback hidden');
  await page.getByTestId('version-detail-1').click();await settle();await expect(page.getByTestId('version-detail')).toContainText('V1',{timeout:20000});await page.locator('.el-dialog:visible .el-dialog__headerbtn').click();
  await select(page.getByTestId('compare-left'),'V1');await select(page.getByTestId('compare-right'),'V3');await page.getByTestId('compare-run').click();await expect(page.getByTestId('version-diff')).toContainText('包装');check(role+' compares snapshots');
  const denial=await page.evaluate(async({api,bid,authorization,target,current})=>(await(await fetch(api+'/passport-batches/'+bid+'/publication/rollback',{method:'POST',headers:{Authorization:authorization,'Content-Type':'application/json'},body:JSON.stringify({target_revision_id:target,expected_current_revision_id:current,idempotency_key:crypto.randomUUID(),rollback_reason:'Browser role verification'})})).json()),{api,bid,authorization,target:vs[0].revision.id,current:vs[2].revision.id});check(role+' direct browser rollback 403',denial.code===403);
 }
 await login('admin');await goBatch();await page.getByTestId('version-detail-1').click();await page.getByTestId('version-verify').click();await expect(page.getByTestId('version-integrity')).toContainText('验证通过');check('Admin real integrity verify');await page.locator('.el-dialog:visible .el-dialog__headerbtn').click();
 await page.getByTestId('rollback-1').click();await page.getByTestId('history-reason').fill('T10 browser restore approved V1 business content');const response=page.waitForResponse(r=>r.url().endsWith('/publication/rollback')&&r.request().method()==='POST');await page.getByTestId('history-confirm').click();const result=await(await response).json();check('Browser V3 to V1 creates V4',result.code===200&&result.data.revision.version_number===4&&result.data.record.publish_status==='published');await settle();await expect(page.getByTestId('published-current')).toContainText('V4');await expect(page.getByTestId('version-history')).toContainText('回滚来源 V1');
 await select(page.getByTestId('compare-left'),'V3');await select(page.getByTestId('compare-right'),'V4');await page.getByTestId('compare-run').click();await expect(page.getByTestId('version-diff')).toContainText('变化');await page.reload();await settle();await expect(page.getByTestId('published-current')).toContainText('V4');check('Browser refresh preserves V4/history');
 }else{
 await login('admin');await goBatch();await expect(page.getByTestId('history-health')).toContainText('需要对账恢复');await expect(page.getByTestId('publish-open')).toHaveCount(0);await expect(page.getByTestId('rollback-1')).toHaveCount(0);check('Pending recovery blocks browser publish rollback');
 await page.getByTestId('history-reconcile').click();await page.getByTestId('history-reason').fill('Finalize verified T10 interrupted rollback after actual backend restart');const response=page.waitForResponse(r=>r.url().endsWith('/publication/reconcile'));await page.getByTestId('history-confirm').click();const result=await(await response).json();check('Browser reconcile succeeds',result.code===200&&result.data.record.publish_status==='published');await settle();await expect(page.getByTestId('history-health')).toContainText('一致');await expect(page.getByTestId('published-current')).toContainText('V5');check('Browser recovered current V5');
 }
 await page.setViewportSize({width:1280,height:900});check('No horizontal page overflow',await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth));await page.getByTestId('history-panel').screenshot({path:rt+'/test-artifacts/browser-history'+(smoke?'-smoke':recovery?'-recovery':'')+'.png'});check('No uncaught browser JS errors',errors.length===0);
}catch(e){console.error(e);checks.push({name:'Browser completed',status:'FAIL',error:e.message});if(page)await page.screenshot({path:rt+'/test-artifacts/browser-failure.png',fullPage:true});process.exitCode=1}finally{fs.writeFileSync(rt+'/test-artifacts/browser'+(smoke?'-smoke':recovery?'-recovery':'')+'-tests.json',JSON.stringify({checks,errors},null,2));await browser.close()}
})();
