T5_ROOT=/path/to/ID
export PATH="$T5_ROOT/runtime/t4/tools/go/bin:$T5_ROOT/runtime/t4/tools/pnpm/node_modules/.bin:$PATH"
export GOPATH="$T5_ROOT/runtime/t5/gopath"
export GOMODCACHE="$T5_ROOT/runtime/t4/gomodcache"
export GOCACHE="$T5_ROOT/runtime/t5/cache/go"
export GOTOOLCHAIN=local
export CGO_ENABLED=1
export GOPROXY=https://goproxy.cn,direct
export GOSUMDB=sum.golang.org
