export const languages=['en','zh-CN'];
const keys=['product','raw_material','process','batch','inspection','certifications','packaging','storage','manufacturer','assets','publication','version','issued_at','schema_version','retry','missing_image','pass','fail','not_tested','not_applicable','pending','informational'];
const rows={
en:['Product information','Raw material','Process','Batch information','Inspection / Quality','Certifications','Packaging','Storage','Manufacturer / Company','Published assets','Publication information','Published version','Published date','Schema','Retry','Image unavailable','Pass','Fail','Not tested','Not applicable','Pending','Informational'],
'zh-CN':['产品信息','原料','生产工艺','批次信息','检验 / 质量','认证','包装','储存','制造商 / 公司','公开图片','发布信息','发布版本','发布日期','数据格式','重试','图片暂不可用','合格','不合格','未检测','不适用','待定','参考信息'],
es:['Información del producto','Materia prima','Proceso','Información del lote','Inspección / Calidad','Certificaciones','Embalaje','Almacenamiento','Fabricante / Empresa','Imágenes publicadas','Publicación','Versión publicada','Fecha de publicación','Esquema','Reintentar','Imagen no disponible','Conforme','No conforme','No analizado','No aplicable','Pendiente','Informativo'],
ar:['معلومات المنتج','المواد الخام','عملية الإنتاج','معلومات الدفعة','الفحص / الجودة','الشهادات','التعبئة','التخزين','الشركة المصنعة','الصور المنشورة','معلومات النشر','النسخة المنشورة','تاريخ النشر','المخطط','إعادة المحاولة','الصورة غير متاحة','مطابق','غير مطابق','لم يُختبر','لا ينطبق','قيد الانتظار','للمعلومات'],
fr:['Informations produit','Matière première','Procédé','Informations du lot','Inspection / Qualité','Certifications','Emballage','Stockage','Fabricant / Entreprise','Images publiées','Publication','Version publiée','Date de publication','Schéma','Réessayer','Image indisponible','Conforme','Non conforme','Non testé','Sans objet','En attente','Informatif'],
de:['Produktinformationen','Rohstoff','Verfahren','Chargeninformationen','Prüfung / Qualität','Zertifizierungen','Verpackung','Lagerung','Hersteller / Unternehmen','Veröffentlichte Bilder','Veröffentlichung','Veröffentlichte Version','Veröffentlichungsdatum','Schema','Erneut versuchen','Bild nicht verfügbar','Bestanden','Nicht bestanden','Nicht geprüft','Nicht zutreffend','Ausstehend','Informativ']};
export function label(key,language='en'){const i=keys.indexOf(key);return i<0?key.replaceAll('_',' ').replace(/^./,c=>c.toUpperCase()):(rows[language]??rows.en)[i];}
