export const languages=['en','zh-CN'];
const keys=['product','raw_material','process','batch','inspection','certifications','packaging','storage','manufacturer','assets','publication','version','issued_at','schema_version','retry','missing_image','pass','fail','not_tested','not_applicable','pending','informational'];
const rows={
en:['Product information','Raw material','Process','Batch information','Inspection / Quality','Certifications','Packaging','Storage','Manufacturer / Company','Published assets','Publication information','Published version','Published date','Schema','Retry','Image unavailable','Pass','Fail','Not tested','Not applicable','Pending','Informational'],
'zh-CN':['产品信息','原料','生产工艺','批次信息','检验 / 质量','认证','包装','储存','制造商 / 公司','公开图片','发布信息','发布版本','发布日期','数据格式','重试','图片暂不可用','合格','不合格','未检测','不适用','待定','参考信息'],
es:['Información del producto','Materia prima','Proceso','Información del lote','Inspección / Calidad','Certificaciones','Embalaje','Almacenamiento','Fabricante / Empresa','Imágenes publicadas','Publicación','Versión publicada','Fecha de publicación','Esquema','Reintentar','Imagen no disponible','Conforme','No conforme','No analizado','No aplicable','Pendiente','Informativo'],
ar:['معلومات المنتج','المواد الخام','عملية الإنتاج','معلومات الدفعة','الفحص / الجودة','الشهادات','التعبئة','التخزين','الشركة المصنعة','الصور المنشورة','معلومات النشر','النسخة المنشورة','تاريخ النشر','المخطط','إعادة المحاولة','الصورة غير متاحة','مطابق','غير مطابق','لم يُختبر','لا ينطبق','قيد الانتظار','للمعلومات'],
fr:['Informations produit','Matière première','Procédé','Informations du lot','Inspection / Qualité','Certifications','Emballage','Stockage','Fabricant / Entreprise','Images publiées','Publication','Version publiée','Date de publication','Schéma','Réessayer','Image indisponible','Conforme','Non conforme','Non testé','Sans objet','En attente','Informatif'],
de:['Produktinformationen','Rohstoff','Verfahren','Chargeninformationen','Prüfung / Qualität','Zertifizierungen','Verpackung','Lagerung','Hersteller / Unternehmen','Veröffentlichte Bilder','Veröffentlichung','Veröffentlichte Version','Veröffentlichungsdatum','Schema','Erneut versuchen','Bild nicht verfügbar','Bestanden','Nicht bestanden','Nicht geprüft','Nicht zutreffend','Ausstehend','Informativ']};
const fieldLabels={
code:'编码',name:'名称',category_code:'产品分类',country_of_origin:'原产国',production_date:'生产日期',expiry_date:'有效期至',quality_status:'质量状态',description:'说明',origin:'原料来源',type:'类型',type_code:'包装类型',quantity:'净含量',unit:'单位',inner_material:'内包装材料',conditions:'储存条件',shelf_life_days:'保质期（天）',shelf_life_description:'保质期说明',address:'地址',certificate_number:'证书编号',issuer:'签发机构',valid_from:'生效日期',valid_until:'有效期至',status:'状态',numeric_value:'检测值',text_value:'检测结果',standard_value:'标准值',min_limit:'下限',max_limit:'上限',specification:'规格要求',test_method:'检测方法',tested_on:'检测日期',judgement:'判定',result_display_text:'检测结果',version_number:'版本',caption:'图片说明',label:'名称',title:'标题',value:'内容',record_type:'记录类型'
};
const messages={
identity:['Product Digital Identity','产品数字身份证'],language:['Language','语言'],working_notice:['Draft preview · Not published','草稿预览 · 尚未发布'],review_notice:['Review preview · Not published','审核预览 · 尚未发布'],test_notice:['Test record · Not for commercial use','测试记录 · 不用于商业用途'],process_expand:['View process steps','展开工艺流程'],steps:['steps','个步骤'],not_found:['Passport not found','未找到产品身份证'],unsupported_schema:['Unsupported passport version','暂不支持此版本'],unavailable:['Passport temporarily unavailable','产品身份证暂时无法访问'],error_help:['Please try again later or contact the supplier.','请稍后重试或联系供应商。']
};
export function label(key,language='en'){if(messages[key])return messages[key][language==='zh-CN'?1:0];if(language==='zh-CN'&&fieldLabels[key])return fieldLabels[key];const i=keys.indexOf(key);return i<0?key.replaceAll('_',' ').replace(/^./,c=>c.toUpperCase()):(rows[language]??rows.en)[i];}
export function displayValue(key,value,language){if(language!=='zh-CN')return value;if(key==='type_code')return ({bag:'袋装',box:'盒装',carton:'纸箱装',bulk:'散装',drum:'桶装'})[value]??value;if(key==='country_of_origin'){try{return new Intl.DisplayNames(['zh-CN'],{type:'region'}).of(value)}catch{return value}}return value;}
