ALTER TABLE passport_revisions ADD COLUMN source_review_record_id TEXT REFERENCES review_records(id) ON DELETE RESTRICT;
ALTER TABLE publish_records ADD COLUMN source_review_record_id TEXT REFERENCES review_records(id) ON DELETE RESTRICT;
CREATE INDEX ix_passport_review ON passport_revisions(source_review_record_id);
CREATE INDEX ix_publish_review ON publish_records(source_review_record_id);
CREATE UNIQUE INDEX ux_review_published_once ON passport_revisions(source_review_record_id) WHERE published_at IS NOT NULL AND source_review_record_id IS NOT NULL;
CREATE TRIGGER passport_review_insert BEFORE INSERT ON passport_revisions WHEN NEW.source_review_record_id IS NULL OR NOT EXISTS(SELECT 1 FROM review_records r WHERE r.id=NEW.source_review_record_id AND r.batch_id=NEW.batch_id AND r.decision='approved' AND r.candidate_hash=NEW.source_content_hash AND r.candidate_input=NEW.frozen_input AND r.reviewed_by=NEW.reviewed_by AND r.reviewed_at=NEW.reviewed_at AND r.source_edit_version=NEW.source_edit_version) BEGIN SELECT RAISE(ABORT,'approved frozen review required'); END;
CREATE TRIGGER passport_review_fixed BEFORE UPDATE ON passport_revisions WHEN NEW.source_review_record_id IS NOT OLD.source_review_record_id BEGIN SELECT RAISE(ABORT,'review source immutable'); END;
CREATE TRIGGER publish_review_insert BEFORE INSERT ON publish_records WHEN NEW.source_review_record_id IS NULL OR NOT EXISTS(SELECT 1 FROM passport_revisions p WHERE p.id=NEW.passport_revision_id AND p.source_review_record_id=NEW.source_review_record_id) BEGIN SELECT RAISE(ABORT,'publish review mismatch'); END;
CREATE TRIGGER publish_identity_fixed BEFORE UPDATE ON publish_records WHEN NEW.id IS NOT OLD.id OR NEW.batch_id IS NOT OLD.batch_id OR NEW.passport_revision_id IS NOT OLD.passport_revision_id OR NEW.source_review_record_id IS NOT OLD.source_review_record_id OR NEW.release_identifier IS NOT OLD.release_identifier OR NEW.idempotency_key IS NOT OLD.idempotency_key OR NEW.expected_current_revision_id IS NOT OLD.expected_current_revision_id OR NEW.created_by IS NOT OLD.created_by OR NEW.operation_type IS NOT OLD.operation_type BEGIN SELECT RAISE(ABORT,'publish identity immutable'); END;
