const {chromium,expect}=require('../go-admin-ui/node_modules/@playwright/test');const fs=require('fs'),path=require('path'),rt=path.resolve(__dirname,'../../runtime/t11'),base='http://127.0.0.1:19540';
(async()=>{const browser=await chromium.launch({executablePath:'/Users/lostar/Library/Caches/ms-playwright/chromium-1228/chrome-mac-arm64/Google Chrome for Testing.app/Contents/MacOS/Google Chrome for Testing',headless:true});let page;const checks=[];const check=(name,v=true)=>{checks.push({name,status:v?'PASS':'FAIL'});if(!v)throw Error(name)};
try{
 const ctx=await browser.newContext();page=await ctx.newPage();await page.route('**/published/*.json',async r=>{await new Promise(resolve=>setTimeout(resolve,1200));await r.continue()});await page.goto(base+'/b/PF-T11-TEST-001');await expect(page.locator('#boot-state')).toContainText('Loading');check('Slow network loading state');await expect(page.locator('[data-module=publication]')).toBeVisible();check('Slow network resolves');await page.unroute('**/published/*.json');
 await page.route('**/js/app.mjs',r=>r.abort());await page.goto(base+'/b/PF-T11-TEST-001');await expect(page.locator('h1')).toHaveText('Passport temporarily unavailable',{timeout:14000});check('Module download failure finite safe fallback');await ctx.close();
 const nojs=await browser.newContext({javaScriptEnabled:false});page=await nojs.newPage();await page.goto(base+'/b/PF-T11-TEST-001');await expect(page.locator('h1')).toHaveText('Passport temporarily unavailable');check('No JS static safe fallback');await nojs.close();
 const c=await browser.newContext();page=await c.newPage();await page.goto(base+'/b/PF-T11-TEST-001');await expect(page.locator('[data-module=publication]')).toBeVisible();const raw=fs.readFileSync(rt+'/publish/published/PF-T11-TEST-001.json','utf8');const results=await page.evaluate(async raw=>{const {renderPassport,localized}=await import('/js/render.mjs');const p=JSON.parse(raw);const r=document.createElement('div');for(const group of ['raw_material','packaging','storage','manufacturer'])for(const k of Object.keys(p[group]))p[group][k]=null;p.process=[];p.inspection=[];p.custom_sections=[];p.assets=[];p.localization.translations=[];p.localization.available_languages=['en'];renderPassport(r,p);return {optional:!r.querySelector('[data-module=raw_material]')&&!r.querySelector('[data-module=manufacturer]'),noNull:!r.textContent.includes('undefined')&&!r.textContent.includes('null')};},raw);for(const [k,v]of Object.entries(results))check('Optional module '+k,v);
 const heading=await page.locator('h1').textContent();await page.selectOption('#language','ar');check('Arabic technical codes LTR',await page.locator('.badge.technical').evaluate(n=>getComputedStyle(n).direction)==='ltr');await page.reload();await expect(page.locator('html')).toHaveAttribute('lang','ar');check('Language URL survives refresh');await page.goto(base+'/b/PF-T11-TEST-001?lang=unknown');await expect(page.locator('h1')).toHaveText(heading);check('Unknown locale defaults EN');await c.close();
}catch(e){checks.push({name:'Edges complete',status:'FAIL',error:e.message});console.error(e);process.exitCode=1;}finally{fs.writeFileSync(rt+'/test-artifacts/browser-edges.json',JSON.stringify(checks,null,2));await browser.close();}})();
