const {chromium,expect}=require('../go-admin-ui/node_modules/@playwright/test');const fs=require('fs'),path=require('path'),rt=path.resolve(__dirname,'../../runtime/t11');
(async()=>{const browser=await chromium.launch({executablePath:'/Users/lostar/Library/Caches/ms-playwright/chromium-1228/chrome-mac-arm64/Google Chrome for Testing.app/Contents/MacOS/Google Chrome for Testing',headless:true});const checks=[],errors=[],cred=JSON.parse(fs.readFileSync(rt+'/credentials.json')),users=JSON.parse(fs.readFileSync(rt+'/test-artifacts/users.json')),f=JSON.parse(fs.readFileSync(rt+'/test-artifacts/fixtures.json'));let page,ctx;
const check=(name,v=true)=>{checks.push({name,status:v?'PASS':'FAIL'});console.log(name,v);if(!v)throw Error(name)};
try{for(const [role,kind,weight]of [['editor','working','20'],['reviewer','review','22']]){
 ctx=await browser.newContext({locale:'zh-CN',viewport:{width:1440,height:1100},permissions:['clipboard-read','clipboard-write']});page=await ctx.newPage();page.setDefaultTimeout(15000);page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error'&&!m.text().includes('Failed to load resource'))errors.push(m.text())});await page.goto('http://127.0.0.1:19539/#/login');await page.locator('input[name=username]').fill(users[role].username);await page.locator('input[name=password]').fill(cred.test_password);for(const el of await page.locator('input').all()){const n=await el.getAttribute('name');if(n!=='username'&&n!=='password'&&await el.isVisible())await el.fill('0');}await page.locator('button.submit-btn').click();await page.waitForURL(u=>u.hash.includes('/dashboard'));await page.goto('http://127.0.0.1:19539/#/passport/batches?batch='+f.preview.id);await page.reload();await expect(page.getByTestId('preview-working')).toBeVisible();
 if(kind==='review')await page.getByTestId('preview-review-select').selectOption(f.review_id);
 await page.getByTestId('preview-'+kind).click();const content=page.getByTestId('private-passport');await expect(content.locator('[data-module=packaging]')).toContainText(weight);check(role+' '+kind+' '+weight+'kg shared renderer');await expect(content.locator('.preview-notice')).toContainText('NOT PUBLISHED');check('Private watermark '+kind);await expect(content.locator('[data-module=publication]')).toHaveCount(0);check('Private builder placeholder not displayed '+kind);await page.screenshot({path:rt+'/test-artifacts/preview-'+kind+'.png',fullPage:true});await page.locator('.el-dialog__headerbtn').last().click();
 check('QR stable code only',await page.getByTestId('qr-target').textContent()==='http://127.0.0.1:19540/b/PF-T11-TEST-PREVIEW');await page.getByTestId('copy-stable').click();check('Clipboard stable',await page.evaluate(()=>navigator.clipboard.readText())==='http://127.0.0.1:19540/b/PF-T11-TEST-PREVIEW');await page.getByTestId('copy-version').click();check('Clipboard version',await page.evaluate(()=>navigator.clipboard.readText())==='http://127.0.0.1:19540/b/PF-T11-TEST-PREVIEW/v/1');
 const popupPromise=page.waitForEvent('popup');await page.getByTestId('view-published').click();const popup=await popupPromise;await expect(popup.locator('[data-module=packaging]')).toContainText('25');check('Published preview actual static 25kg');check('Published opener detached',await popup.evaluate(()=>window.opener===null));await popup.close();
 await page.evaluate(()=>Object.defineProperty(navigator,'clipboard',{value:undefined,configurable:true}));await page.getByTestId('copy-stable').click();await expect(page.locator('.el-message').last()).toContainText('无法访问剪贴板');check('Clipboard failure shown');
 await page.locator('.avatar-wrapper').hover();await page.getByText('退出登录',{exact:true}).click();await page.locator('.el-message-box__btns .el-button--primary').click();await page.waitForURL(u=>u.hash.includes('/login'));check('Actual logout '+role);await ctx.close();
 }check('Admin browser no errors',errors.length===0);
}catch(e){console.error(e);checks.push({name:'Preview browser complete',status:'FAIL',error:e.message});process.exitCode=1;if(page)await page.screenshot({path:rt+'/test-artifacts/preview-failure.png',fullPage:true});}finally{fs.writeFileSync(rt+'/test-artifacts/preview-browser.json',JSON.stringify({checks,errors},null,2));await browser.close();}})();
