from pathlib import Path
import json,re,datetime,hashlib,sqlite3
R=Path(__file__).resolve().parents[2];rt=R/'runtime/t12';art=rt/'test-artifacts';request=Path('/Users/lostar/.codex/attachments/9e4cc63e-8385-4e6e-aed7-412178efab12/pasted-text.txt').read_text()
suites=[]
for name in ['flow-prepare','flow-resume_prepare','browser-submit','flow-pending','browser-reject','flow-rejected','flow-v1','flow-revisions','versions','concurrency','failure-api','browser-full','browser-admin-pages','http-checks','static-checks','migration-backup','backup-restore','final-verify','offline-verify','browser-stopped','independence','stopped']:
 d=json.loads((art/(name+'.json')).read_text());checks=d if isinstance(d,list) else d['checks'];suites.append({'name':name,'checks':checks,'pass':sum(x['status']=='PASS' for x in checks),'fail':sum(x['status']=='FAIL' for x in checks),'evidence':'runtime/t12/test-artifacts/'+name+'.json'})
suites += [{'name':'Go injected faults','pass':3,'fail':0,'evidence':'runtime/t12/logs/faults.log'},{'name':'UI unit','pass':301,'fail':0,'evidence':'runtime/t12/logs/ui-ci.log'},{'name':'UI lint/type/i18n','pass':3,'fail':0,'evidence':'runtime/t12/logs/ui-ci.log; runtime/t12/logs/ui-i18n.log'},{'name':'UI test:ci contract command','pass':0,'fail':1,'evidence':'runtime/t12/logs/ui-ci.log'},{'name':'Required media business entry','pass':0,'fail':1,'evidence':'docs/T9_PUBLISH_ENGINE.md:36; existing API router has no MediaAsset/AssetLink business entry'}]
failures={25:'正式媒体上传/关联入口不存在，本轮 MediaAsset/PublishedAsset 均为0；未用SQL图片夹具绕过。',32:'按顺序从 Published 主批次 Clone，API409：仅允许编辑未锁定的 Draft 批次；PF-T12-TEST-003未建立。',35:'字段、检验与模块差异已验证，但没有实际图片变更，资产差异子项未覆盖。',43:'本轮注入了共用发布执行器的 Rollback build 故障；未单独覆盖普通 Publish 构建失败，不提升为完整通过。',50:'没有真实媒体输入，无法验证损坏 Published Asset。',60:'静态JSON、前端与私有Manifest已独立备份；图片备份缺少真实样本。',61:'静态恢复后的无图片页面已通过；图片恢复访问未验证。',62:'后台停止后的无图片页面通过；图片独立性未验证。',63:'SQLite路径不可访问时无图片页面通过；图片独立性未验证。',64:'Nginx重启及恢复根访问通过；图片子项未验证。',66:'Version immutable/ETag已通过；Asset immutable缺少实际图片响应。',83:'资产集合为空，不能以空集遍历声称全量 Asset Hash 验收通过。'}
evidence={}
def assign(ids,ev):
 for i in ids:evidence[i]=ev
assign([1,2], 'logs/migrate-first.log; test-artifacts/environment.json')
assign([3], 'test-artifacts/migration-backup.json')
assign([4,5,6,7,8,9,10,11,12,13,14,15,16], 'test-artifacts/flow-prepare.json; flow-resume_prepare.json; browser-submit.json')
assign([17,18,19,20,21,22], 'test-artifacts/browser-submit.json; flow-pending.json; browser-reject.json; flow-v1.json; concurrency.json')
assign([23,24], 'test-artifacts/flow-v1.json; final-verify.json')
assign([26,27,28,29,67,68,69,70,71,73,74,75,78,79], 'test-artifacts/browser-full.json; browser-stopped.json')
assign([30,31], 'test-artifacts/flow-revisions.json')
assign([33,34,36,37,38,39,40,41,42], 'test-artifacts/versions.json; main-history.json; browser-stopped.json; browser-admin-pages.json')
assign([44,45,46,47,48,49,51], 'logs/faults.log; test-artifacts/failure-api.json')
assign([52,53,54,55,56], 'test-artifacts/concurrency.json')
assign([57,58,59], 'test-artifacts/backup-restore.json')
assign([65,76,77], 'test-artifacts/http-checks.json; browser-stopped.json')
assign([72], 'test-artifacts/browser-admin-pages.json; browser-submit.json; browser-reject.json')
assign([80,81,82,84,86], 'test-artifacts/offline-verify.json; final-verify.json')
assign([85], 'test-artifacts/stopped.json')
assign([87,88,89,90,91,95], '本轮工具操作范围核对；未执行服务器探测')
assign([92,93,94], 'docs/T13_DEPLOYMENT_PRECHECK.md（仅文档）')
segment=request.split('八十七、T12 必过 Gate')[1].split('八十八、')[0];gates=[{'id':int(i),'name':name.strip(),'status':'FAIL' if int(i) in failures else 'PASS','evidence':failures.get(int(i),evidence.get(int(i),'未映射'))} for i,name in re.findall(r'Gate (\d+)：\s*([^\n]+)',segment)];assert len(gates)==95 and not any(g['evidence']=='未映射' for g in gates)
answers={i:'是；本轮对应 Gate 与原始证据见上表。' for i in range(1,111)}
answers.update({1:'是；独立空库执行全部16迁移。',2:'是；重复执行后全部表数据摘要一致。',3:'是；四角色重新登录并进行权限请求，另验证组合角色不可自审。',4:'是；正式Product API创建，浏览器查看。',5:'是；R1真实创建，R2真实Clone。',6:'是；单套Product/Revision下有en、zh-CN、es、ar、fr、de。',7:'四种结构与渲染通过；asset_gallery无图，图片链未通过。',13:'是；五项动态检验按行保存，无新增Schema。',18:'是；真实Reviewer UI执行指定原因的Reject。',19:'是；第一次冻结Hash及精确驳回原因保留。',20:'是；再次提交产生新attempt，旧attempt保留。',22:'是；Approve时无Passport分配，状态ready_for_publish。',24:'无图片V1真实发布通过；不代表含图完整链通过。',26:'是；所有已封存JSON扫描无内部字段，使用正式白名单Builder。',27:'未通过；缺少媒体业务入口，未插入媒体SQL夹具。',30:'是；公开六语言实际浏览器切换。',31:'是；Arabic时html dir=rtl。',32:'是；R2克隆后确认源语言、改30kg、封版与设默认。',35:'未通过；Published源批次Clone API409，未建立003。',36:'未验证；003未建立，不能声称已清空实测值。',37:'是；仅使用第42节明确允许的V2 Candidate Fixture，后续真实编辑/提交/审核/发布。',38:'V1 JSON及Manifest保留；本轮无资产，不能宣称图片保留通过。',40:'部分；核心字段、检测、模块差异通过，实际资产差异未测。',41:'是；V3新ID、新发布记录，来源V1、前头V2。',45:'实际产生的审核、发布、回滚事件可查询；图片/Clone成功事件不存在。',48:'V1 JSON/Manifest通过；Assets为空，图片验收未通过。',49:'V2 JSON/Manifest通过；Assets为空。',50:'V3 JSON/Manifest通过；Assets为空。',51:'普通Publish构建失败未单独重跑；已验证共用执行器Rollback build故障，不认定完整通过。',52:'是；共用执行器rename故障保留旧Current。',53:'是；依赖注入及真实SQLite触发器确认失败均已验证。',54:'是；Admin真实API恢复原操作，不另建版本。',58:'未通过；无实际Published Asset可损坏。',59:'JSON损坏时被拒绝；资产损坏拒绝未验证。',65:'本地单实例、短事务、五请求竞争下仍可用；不足以证明生产负载、多写实例或断电场景。',66:'本轮并发响应与后台日志未出现database is locked；没有切换PostgreSQL。',67:'是；最终SQLite Backup API，时间与SHA见backup-restore.json。',68:'是；恢复到独立runtime/t12/db/restored.db。',69:'是；全部表逐表行数与内容Hash一致，非只核对总行数。',70:'JSON、前端、私有Manifest已单独备份；图片缺少样本。',71:'无图片页面在恢复副本上通过；完整图片访问未通过。',72:'无图片页面通过；图片独立性未验证。',73:'配置DB路径临时移开时无图片页面通过；随后恢复原文件名。',74:'独立Nginx重启后无图片页面通过；图片子项未验证。',76:'是；历史JSON immutable及ETag304。',77:'未验证真实Asset响应，不把Nginx配置存在当验收通过。',83:'功能页面通过；另test:ci的通用API检查失败，详见工具链记录。',84:'是；匿名网络仅本地静态origin，无Admin API。',85:'是；未携带Authorization/JWT。',88:'是；T12非敏感私有探针经symlink无法公开，探针已删除。',91:'ok。',92:'空，无异常。',93:'是；全部9份sealed快照原文字节与DB Hash一致，含1份失败prepared诊断。',94:'未通过；0条资产不构成图片完整性验收。',95:'是；全部9份Manifest逐字段与原始确定编码一致。',96:'No；没有新增业务Schema。',97:'不适用；无新Migration。',98:'No；历史迁移与历史证据Hash未变。',99:'是；53/53哈希一致。',100:'是；原site 7文件不变。',101:'No。',102:'No。',103:'No。',104:'No。',105:'No。',106:'是；仅文档，不能作为T13放行。',107:'是；明确T12通过与单独授权前置。',108:'是；应用/DB/静态目录协同回退，禁止破坏共享服务。',109:'是；18109、18110、19541、19542均未监听。',110:'No；T13/T14均未进入。'})
qs=re.findall(r'^(\d+)\. (.+)$',request.split('八十八、最终逐项回答')[1].split('八十九、')[0],re.M);assert len(qs)==110
report={'stage':'T12','status':'FAIL — 未满足95/95，不能提交通过验收；本轮已停止，未进入T13','generated_at':datetime.datetime.now(datetime.timezone.utc).isoformat(),'gates_pass':sum(g['status']=='PASS' for g in gates),'gates_fail':len(failures),'tests_pass':sum(s['pass'] for s in suites),'tests_fail':sum(s['fail'] for s in suites),'counting':'命名断言+Go叶测试+301 UI单测；测试请求/选择器调试失败保留日志，不计最终套件；缺少证据的Gate保守记FAIL，不等同系统已发生故障。','gates':gates,'suites':suites,'questions':[{'id':int(n),'question':q,'answer':answers[int(n)]} for n,q in qs],'entered_T13':False,'all_local_services_stopped':True,'media_fixture_used':False,'v2_fixture':'T12 section42 explicit exception only'}
(R/'docs/T12_TEST_RESULTS.json').write_text(json.dumps(report,ensure_ascii=False,indent=2))
env=json.loads((art/'environment.json').read_text());sizes=json.loads((art/'sizes.json').read_text());backup=json.loads((art/'backup-restore.json').read_text());f=json.loads((art/'flow-state.json').read_text())
categories={'Fresh Installation':'PASS','Migration':'PASS','RBAC':'PASS','Product Flow':'PASS','Revision Flow':'PASS','Batch Flow':'FAIL','Custom Sections':'FAIL（图像链缺口）','Review Flow':'PASS','Publish Flow':'FAIL（含图完整链未通过）','Public Site':'FAIL（含图完整链未通过）','Version History':'PASS（实际无图版本）','Rollback':'PASS（实际无图版本）','Reconcile':'PASS','Failure Safety':'FAIL（普通Publish构建故障与资产损坏覆盖不足）','Concurrency':'PASS','Backup':'PASS','Restore':'PASS','Static Backup':'FAIL（图像未验证）','Backend Independence':'FAIL（图像未验证）','Security Regression':'PASS（已列明的回归项）','Mobile':'PASS（无图页面）','Performance':'FAIL（最大图片与含图负载未验证）','Integrity':'FAIL（图像未验证）','Baseline Protection':'PASS','Deployment Readiness':'FAIL'}
text='# T12 本地端到端最终总验收执行报告\n\n【T12 执行结果】\n\n**T12 状态：未通过，不能提交95/95通过验收。全部本轮服务已停止；T13未授权、未进入。** T0–T11已由用户人工验收通过。\n\n'
text+='首先区分：前序分阶段验收成立，并不证明本轮新增的从零完整业务链已成立。T9明确没有媒体上传/关联业务入口，T6明确只Clone未锁定Draft；T12要求含图片全链及从Published主批次Clone，与现有已接受范围存在缺口。本轮没有擅自补开发业务入口，也没有使用SQL图片夹具。\n\n'
text+='| 类别 | 结果 |\n|---|---|\n'+'\n'.join(f'| {k} | {v} |' for k,v in categories.items())+'\n\n'
text+=f"Gate：**{report['gates_pass']} / 95 PASS，{report['gates_fail']} FAIL（含缺少完整证据）**。Tests：**{report['tests_pass']} PASS，{report['tests_fail']} FAIL**。计数包含301项上游UI单测与重复快照断言，不等于独立业务场景数。\n\n"
text+='## 确认的阻断与范围\n\n- 媒体：正式MediaAsset/AssetLink上传关联入口缺失，源媒体与PublishedAsset均0。空gallery可建，不等于图片可运营。没有手工插入媒体行或写正常Published产物。图片冻结、换图比较、损坏图拒绝、图片备份/恢复/离线访问均不能PASS。\n- Clone：Published主批次调用正式Clone返回409「仅允许编辑未锁定的 Draft 批次」，003不存在。因此不能声明源R1保留/结果清空已验收。没有将主批次人为改Draft来绕过这个检查。\n- 普通Publish构建前故障未独立覆盖；本轮验证了共用执行器Rollback build/rename/finalize与真实SQLite确认失败，保守不将前者提升为完整普通发布故障通过。\n- 工具链：pnpm test:ci失败于check:api，4处诊断（Batch/QueueRow模型无法解析、产品页匹配DemoProduct、search绑定识别）。真实业务API功能测试通过，但不修改通用检查器来消除报告。lint 0error/30warning、类型检查、301单测通过；i18n单独通过。\n\n'
text+='## 实际环境与数据\n\n'+f"Go {env['go']}；Node {env['node']}；pnpm {env['pnpm']}；Go驱动SQLite {env['go_sqlite']['sqlite_version']}，WAL、FK=1、busy_timeout=5000、synchronous=2(FULL)。Chromium149.0.7827.55；本地Nginx1.30.4（复用已编译只读程序，使用新T12配置与发布根）。\n\n后端commit `{env['backend_commit']}`；UIcommit `{env['ui_commit']}`。环境完整证据：runtime/t12/test-artifacts/environment.json。\n\n"
text+='Fresh DB：`runtime/t12/db/passport-admin-t12.db`，从空库16迁移；独立配置/随机本地JWT/本地测试账户。公开 `runtime/t12/publish`，私有Manifest `runtime/t12/releases/manifests`。主Product `PF-T12-TEST`；主Batch `PF-T12-TEST-001`固定R1，002绑定R2，003未创建。辅助批次仅TEST。\n\n'
text+='角色：admin、独立Editor/Reviewer/Viewer、另组合EditorReviewer；具体测试用户名在私有test-artifacts/users.json，密码不写报告。数据库最终3 Product、9 ProductRevision、5 Batch、7 ReviewRecord、10 PassportRevision/PublishRecord、123 Audit；8成功发布、2失败记录，无待对账记录；9份sealed JSON/Manifest。无媒体行。\n\n'
text+='主版本：\n\n'+'\n'.join(f'- V{i}：`{rid}`，`runtime/t12/publish/versions/PF-T12-TEST-001/v{i}.json`。' for i,rid in enumerate(f['versions'],1))+'\n\n'
text+='V1为20kg，V2为22kg且检测/模块变更，回滚产生新V3恢复V1公开业务内容，保留V1/V2。V2只采用用户第42节明确允许的本地Candidate Fixture清理工作审核指针，保留Current及历史，之后编辑/提交/审核/发布全部真实API；披露见v2-fixture-disclosure.json。它不代表正式Published→Draft功能。\n\n'
text+='## 自动、浏览器、并发与故障证据\n\n| 套件 | PASS | FAIL | 证据 |\n|---|---:|---:|---|\n'+'\n'.join(f"| {s['name']} | {s['pass']} | {s['fail']} | {s['evidence']} |" for s in suites)+'\n\n'
text+='浏览器真实Editor提交、Reviewer冻结预览/指定原因驳回、Admin产品/批次/队列/历史/Verify/审计与退出；无最终浏览器错误。公开六语言/RTL、九步工艺、五检验、四模块结构、375/390/430/1280/1440视口；匿名请求只到本地静态origin，无JWT/Admin API。JSON错误、未知Schema、当前与历史不一致、网络错误重试、XSS纯文本、raw路径穿越、symlink探针均验证。\n\n并发每组5请求：创建Revision、相同BatchCode、Submit、Approve/Reject、Publish、Rollback；无重复版本/双重决定。后台日志与响应无database is locked；这不证明生产高并发或网络盘适用。\n\n故障使用独立辅助批次：Go依赖注入build/rename/finalize；另外实际SQLite触发器使published_at确认失败，经API出现file_switched_db_pending并阻止Publish/Rollback，Admin Reconcile确认原记录。触发器finally删除；历史JSON损坏后Verify失败、Rollback拒绝，原字节finally恢复。故障产物保留诊断，不重用版本号。\n\n'
text+='## Backup / Restore 与独立性\n\n'+f"最终备份时间 `{backup['started_at']}`，SQLite Backup API；`runtime/t12/backups/t12-final.db` SHA256 `{backup['backup_sha256']}`。独立恢复 `runtime/t12/db/restored.db`，全部表行数/数据Hash一致且integrity/FK通过。工作库早期检查点另存，未冒充最终备份。\n\n"
text+='静态发布、public-site、私有releases分别备份；恢复到`runtime/t12/backups/restored-publish`与`restored-public-site`，与源逐文件Hash一致。Nginx换到恢复根并重启；后台/UI已停，配置DB主文件/WAL/SHM暂时移至offline名，公开稳定与V1/V2/V3/六语言仍通过，之后恢复文件名。图片为空，因此相关完整Gates保守FAIL。\n\n'
text+=f"性能：HTML {sizes['html']}B、CSS {sizes['css']}B、JS {sizes['js']}B、最终Current JSON {sizes['json']}B，最大图片未测（无图片，不能称0B图片通过）。T11分别1417/5632/35159/8189B及80B测试图；本轮前三项未变、JSON增加453B，不能拿无图负载与含图负载作等价性能结论。实际资源耗时见performance.json，仅本机样本。\n\n"
text+='## 文件、迁移与基线\n\n新增`admin/t12/`验收脚本、`admin/go-admin/app/passport/service/t12_acceptance_test.go`（仅t12_validation标签）、本轮runtime证据和三份T12/T13文档；修改TASKS阶段状态。无业务源码修复、无新业务Schema/新Migration；没有修改历史Migration。原53文件、POC7文件、31,854个受保护历史文件哈希一致。调试中只修正测试请求的allow_hide/翻译DTO/克隆译文确认与Playwright定位；错误日志保留，不宣称它们是业务修复。\n\n'
text+='T13配置、部署顺序、协同回退方案见[T13_DEPLOYMENT_PRECHECK.md](T13_DEPLOYMENT_PRECHECK.md)。该文档是准备材料，不是部署授权；没有访问SERVER_IP、Caddy、Directus、生产Docker、DNS/HTTPS或生成正式QR。\n\n'
text+='## 95 Gates\n\n| # | 条件 | 结果 | 证据/限制 |\n|---|---|---|---|\n'+'\n'.join(f"| {g['id']} | {g['name']} | {g['status']} | {g['evidence']} |" for g in gates)+'\n\n## 110 项逐项答复\n\n'+'\n\n'.join(f'{n}. **{q}** {answers[int(n)]}' for n,q in qs)+'\n\n本轮T12验收执行已停止，但T12未通过；未达到95/95，不提交为「等待通过人工验收」，未进入T13。用户要求的成功结束语以完成全部Gates为前提，本报告不使用该成功声明。\n'
(R/'docs/T12_END_TO_END_ACCEPTANCE.md').write_text(text)
print(json.dumps({k:report[k] for k in ['gates_pass','gates_fail','tests_pass','tests_fail']},ensure_ascii=False))
