import fs from 'node:fs';import path from 'node:path';import {publicURL} from '../../public-site/js/urls.mjs';import {validatePayload,parseRoute,assetPath} from '../../public-site/js/schema.mjs';
const rt=path.resolve('runtime/t12'),checks=[];const check=(name,v)=>{checks.push({name,status:v?'PASS':'FAIL'});if(!v)throw Error(name)};const rejects=f=>{try{f();return false}catch{return true}};
try{
const url=publicURL('https://example.invalid','PF-T12-TEST-001');check('QR exact stable batch code',url==='https://example.invalid/b/PF-T12-TEST-001');check('QR has no version or DB ID',!url.includes('/v/')&&!url.includes('?'));
check('Config alternate origin',publicURL('https://another.invalid','PF-T12-TEST-001').startsWith('https://another.invalid/'));check('Local explicitly allowed',publicURL('http://127.0.0.1:19542','PF-T12-TEST-001',null,'local').includes(':19542/'));
for(const base of ['http://example.invalid','https://localhost','https://localhost.','https://127.0.0.2','https://[::1]','https://x.localhost','https://user:pw@example.invalid','https://example.invalid/path','https://example.invalid?x=1','javascript:alert(1)'])check('Reject QR base '+base,rejects(()=>publicURL(base,'PF-T12-TEST-001')));
for(const code of ['../test','x/y','%2e%2e','a'.repeat(65),'中文','TEST\n','TEST?x=1','TEST#frag','TEST\\x']){check('Reject QR code '+JSON.stringify(code),rejects(()=>publicURL('https://example.invalid',code)));check('Reject route '+JSON.stringify(code),rejects(()=>parseRoute('/b/'+code)));}
for(const v of ['0','-1','01','1.2','1e2','9007199254740992','1\n'])check('Reject version '+JSON.stringify(v),rejects(()=>publicURL('https://example.invalid','TEST-X',v)));
const p=JSON.parse(fs.readFileSync(rt+'/publish/published/PF-T12-TEST-001.json'));check('Real release schema',validatePayload(p)===p);check('Historical parse exact',parseRoute('/b/PF-T12-TEST-001/v/1').version==='1');
for(const mutate of [p=>p.private_note='secret',p=>p.batch.code='../private',p=>p.schema_version='99.0']){const q=structuredClone(p);mutate(q);check('Reject payload mutation '+checks.length,rejects(()=>validatePayload(q)));}
for(const path of ['file:///etc/passwd','https://example.invalid/a.png','javascript:alert(1)','../../secret'])check('Unsafe asset path rejected '+path,rejects(()=>assetPath({path}))); 
const sizes={html:fs.statSync('public-site/index.html').size,css:fs.statSync('public-site/css/passport.css').size,js:fs.readdirSync('public-site/js').filter(x=>/\.(mjs|js)$/.test(x)).reduce((n,x)=>n+fs.statSync('public-site/js/'+x).size,0),json:fs.statSync(rt+'/publish/published/PF-T12-TEST-001.json').size,images:p.assets.reduce((n,a)=>n+a.file_size,0)};check('Public JS below 150 KiB',sizes.js<153600);fs.writeFileSync(rt+'/test-artifacts/sizes.json',JSON.stringify(sizes,null,2));
}finally{fs.writeFileSync(rt+'/test-artifacts/static-checks.json',JSON.stringify(checks,null,2));console.log(checks.length,'checks');}
