const {chromium,expect}=require('../go-admin-ui/node_modules/@playwright/test');
const fs=require('fs'),path=require('path');const rt=path.resolve(__dirname,'../../runtime/t9');
(async()=>{const fresh=process.argv.includes('fresh');const cred=JSON.parse(fs.readFileSync(rt+'/credentials.json'));const users=JSON.parse(fs.readFileSync(rt+'/test-artifacts/'+(fresh?'fresh-users':'users')+'.json'));const checks=[],errors=[];const url='http://127.0.0.1:'+(fresh?'19535':'19534'),api='http://127.0.0.1:'+(fresh?'18104':'18103')+'/api/v1';const browser=await chromium.launch({executablePath:'/Users/lostar/Library/Caches/ms-playwright/chromium-1228/chrome-mac-arm64/Google Chrome for Testing.app/Contents/MacOS/Google Chrome for Testing',headless:true});let page,ctx,authorization,bid,pid;
const check=(name,value=true)=>{checks.push({name,status:value?'PASS':'FAIL'});console.log(name,value);if(!value)throw Error(name)};
const settle=()=>page.waitForLoadState('networkidle');
async function login(role){if(ctx){await page.locator('.avatar-wrapper').hover();await page.getByText('退出登录',{exact:true}).click();await page.locator('.el-message-box__btns .el-button--primary').click();await page.waitForURL(u=>u.hash.includes('/login'));check('Browser actual logout');await ctx.close();}ctx=await browser.newContext({locale:'zh-CN',viewport:{width:1440,height:1100}});page=await ctx.newPage();page.setDefaultTimeout(15000);page.on('pageerror',e=>errors.push(e.message));page.on('request',r=>{if(r.url().startsWith(api)&&r.headers().authorization)authorization=r.headers().authorization});await page.route('**/*',r=>{const u=new URL(r.request().url());return ['127.0.0.1','localhost'].includes(u.hostname)||['data:','blob:'].includes(u.protocol)?r.continue():r.abort()});await page.goto(url+'/#/login',{waitUntil:'networkidle'});await page.locator('input[name=username]').fill(role==='admin'?cred.admin_username:users[role].username);await page.locator('input[name=password]').fill(role==='admin'?cred.admin_password:cred.test_password);for(const el of await page.locator('input').all()){const n=await el.getAttribute('name');if(!['username','password'].includes(n)&&await el.isVisible())await el.fill('0')};await page.locator('button.submit-btn').click();await page.waitForURL(u=>u.hash.includes('/dashboard'));await settle();check('Browser '+role+' login')}
async function read(p){return(await(await page.request.get(api+'/'+p,{headers:{Authorization:authorization}})).json()).data}
async function select(el,text){await el.scrollIntoViewIfNeeded();await el.click();const dd=page.locator('.el-select-dropdown:visible');await dd.getByText(text,{exact:true}).waitFor();for(let i=0;i<110;i++){await page.keyboard.press('ArrowDown');const h=dd.locator('.is-hovering');if(await h.count()&&await h.first().innerText()===text){await page.keyboard.press('Enter');return}}throw Error('select '+text)}
async function review(action,reason='',success=true){await page.getByTestId('review-'+action).click();if(reason)await page.getByTestId('review-reason').fill(reason);const promise=page.waitForResponse(r=>r.url().endsWith('/review/'+action)&&r.request().method()==='POST');await page.getByTestId('review-confirm').click();const result=await(await promise).json();if(result.code!==(success?200:403)) console.log('review response',result.code,result.msg);check('Browser '+action+(success?'':' self denied'),result.code===(success?200:403));if(success)await expect(page.getByTestId('review-confirm')).toBeHidden();await settle()}
const fixture=(action)=>{const p=require('child_process').spawnSync('python3',[path.join(__dirname,'browser_fixture.py'),action,bid],{encoding:'utf8'});if(p.status!==0)throw Error('fixture '+action+': '+p.stderr);return JSON.parse(p.stdout)};
async function goBatch(){await page.goto(url+'/#/passport/batches?batch='+bid);await page.reload();await page.getByTestId('review-state').waitFor();await settle()}
async function doPublish(expected){await page.getByTestId('publish-open').click();await page.evaluate(()=>{window.__t9PublishingSeen=false;new MutationObserver(()=>{if(document.querySelector('[data-testid="publishing-state"]'))window.__t9PublishingSeen=true}).observe(document.body,{subtree:true,childList:true})});const response=page.waitForResponse(r=>r.url().endsWith('/publication')&&r.request().method()==='POST');await page.getByTestId('publish-confirm').click();const result=await(await response).json();check('Browser publish result '+expected,result.code===200&&result.data.record.publish_status===expected);await expect(page.getByTestId('publish-confirm')).toBeHidden();await settle();check('Browser displayed Publishing',await page.evaluate(()=>window.__t9PublishingSeen));return result.data}
try{
 await login('editor');await page.goto(url+'/#/passport/products');await page.getByTestId('create-product').click();const code='TEST-P-T9-UI-'+Date.now();await page.getByTestId('new-code').fill(code);await page.getByTestId('new-name').fill('T9 BROWSER TEST ONLY');await page.getByTestId('confirm-create').click();await page.getByTestId('selected-revision').waitFor();await settle();pid=new URLSearchParams(page.url().split('?')[1]).get('product');await page.getByTestId('translation-approved').click();await page.getByTestId('save-translation').click();await settle();await page.getByTestId('seal-revision').click();await page.locator('.el-message-box__btns .el-button--primary').click();await settle();await page.getByTestId('set-default').click();await settle();check('Browser Editor creates/seals Product');
 await page.goto(url+'/#/passport/batches');await page.getByTestId('create-batch').click();await select(page.getByTestId('new-batch-product'),code);await page.getByTestId('new-batch-code').fill('TEST-T9-UI-'+Date.now());for(const [label,value] of [['生产日期','2026-09-10'],['有效期','2027-09-10']]){const input=page.locator('.el-dialog:visible .el-form-item').filter({has:page.locator('label',{hasText:label})}).locator('input');await input.fill(value);await input.press('Enter')};await page.getByTestId('confirm-batch-create').click();await page.getByTestId('batch-heading').waitFor();await settle();bid=new URLSearchParams(page.url().split('?')[1]).get('batch');check('Browser Editor creates Draft');fixture('asset');await goBatch();await review('submit');await expect(page.getByTestId('review-state')).toContainText('待审核');await expect(page.getByTestId('review-frozen-asset').locator('img')).toBeVisible();check('Frozen image reviewed before publish');
 await login('reviewer');await page.goto(url+'/#/passport/reviews?batch='+bid);await page.getByTestId('review-state').waitFor();await expect(page.getByTestId('review-frozen-asset').locator('img')).toBeVisible();await review('approve');await expect(page.getByTestId('review-state')).toContainText('待发布');check('Reviewer approves actual candidate');
 for(const role of ['editor','reviewer']){await login(role);await goBatch();await expect(page.getByTestId('publish-open')).toHaveCount(0);const rv=(await read('passport-batches/'+bid+'/review')).current;const denial=await page.evaluate(async({api,bid,authorization,rv})=>(await(await fetch(api+'/passport-batches/'+bid+'/publication',{method:'POST',headers:{Authorization:authorization,'Content-Type':'application/json'},body:JSON.stringify({review_id:rv.id,candidate_hash:rv.candidate_hash,idempotency_key:crypto.randomUUID(),expected_current_revision_id:null})})).json()),{api,bid,authorization,rv});check('Browser '+role+' publish 403',denial.code===403)}
 await login('admin');await goBatch();const hashText=await page.getByTestId('review-hash').innerText();check('Admin sees candidate hash',/[0-9a-f]{64}/.test(hashText));const success=await doPublish('published');await expect(page.getByTestId('published-current')).toContainText('V1');await expect(page.getByTestId('published-hash')).toContainText(success.revision.payload_hash);await expect(page.getByTestId('published-asset-count')).toHaveText('1');await page.reload();await settle();await expect(page.getByTestId('published-current')).toContainText('V1');check('Browser published V1/hash/count persist on refresh');await page.setViewportSize({width:1280,height:900});check('No horizontal overflow',await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth));await page.screenshot({path:rt+'/test-artifacts/browser-published.png',fullPage:true});
 fixture('failure');await goBatch();await doPublish('failed');await expect(page.getByTestId('publish-error')).toBeVisible();await expect(page.getByTestId('published-hash')).toContainText(success.revision.payload_hash);await expect(page.getByTestId('publish-open')).toBeEnabled();check('Browser failure keeps old Current and retry available');await page.screenshot({path:rt+'/test-artifacts/browser-failed.png',fullPage:true});fixture('restore');await doPublish('published');check('Browser explicit retry succeeds');check('No uncaught browser JS errors',errors.length===0);fs.writeFileSync(rt+'/test-artifacts/browser-fixtures.json',JSON.stringify({pid,bid,first:success}));
}catch(e){console.error(e);checks.push({name:'Browser completed',status:'FAIL',error:e.message});if(page)await page.screenshot({path:rt+'/test-artifacts/browser-failure.png',fullPage:true});process.exitCode=1}finally{fs.writeFileSync(rt+'/test-artifacts/browser-tests.json',JSON.stringify({checks,errors},null,2));await browser.close()}
})();
