const {chromium,expect}=require('../go-admin-ui/node_modules/@playwright/test');
const fs=require('fs'),path=require('path');const rt=path.resolve(__dirname,'../../runtime/t9');
(async()=>{const fresh=process.argv.includes('fresh');const cred=JSON.parse(fs.readFileSync(rt+'/credentials.json'));const users=JSON.parse(fs.readFileSync(rt+'/test-artifacts/'+(fresh?'fresh-users':'users')+'.json'));const checks=[],errors=[];const url='http://127.0.0.1:'+(fresh?'19535':'19534'),api='http://127.0.0.1:'+(fresh?'18104':'18103')+'/api/v1';const browser=await chromium.launch({executablePath:'/Users/lostar/Library/Caches/ms-playwright/chromium-1228/chrome-mac-arm64/Google Chrome for Testing.app/Contents/MacOS/Google Chrome for Testing',headless:true});let page,ctx,authorization,bid,pid;
const check=(name,value=true)=>{checks.push({name,status:value?'PASS':'FAIL'});console.log(name,value);if(!value)throw Error(name)};
const settle=()=>page.waitForLoadState('networkidle');
async function login(role){if(ctx){await page.locator('.avatar-wrapper').hover();await page.getByText('退出登录',{exact:true}).click();await page.locator('.el-message-box__btns .el-button--primary').click();await page.waitForURL(u=>u.hash.includes('/login'));check('Browser actual logout');await ctx.close();}ctx=await browser.newContext({locale:'zh-CN',viewport:{width:1440,height:1100}});page=await ctx.newPage();page.setDefaultTimeout(15000);page.on('pageerror',e=>errors.push(e.message));page.on('request',r=>{if(r.url().startsWith(api)&&r.headers().authorization)authorization=r.headers().authorization});await page.route('**/*',r=>{const u=new URL(r.request().url());return ['127.0.0.1','localhost'].includes(u.hostname)||['data:','blob:'].includes(u.protocol)?r.continue():r.abort()});await page.goto(url+'/#/login',{waitUntil:'networkidle'});await page.locator('input[name=username]').fill(role==='admin'?cred.admin_username:users[role].username);await page.locator('input[name=password]').fill(role==='admin'?cred.admin_password:cred.test_password);for(const el of await page.locator('input').all()){const n=await el.getAttribute('name');if(!['username','password'].includes(n)&&await el.isVisible())await el.fill('0')};await page.locator('button.submit-btn').click();await page.waitForURL(u=>u.hash.includes('/dashboard'));await settle();check('Browser '+role+' login')}
async function read(p){return(await(await page.request.get(api+'/'+p,{headers:{Authorization:authorization}})).json()).data}
async function select(el,text){await el.scrollIntoViewIfNeeded();await el.click();const dd=page.locator('.el-select-dropdown:visible');await dd.getByText(text,{exact:true}).waitFor();for(let i=0;i<110;i++){await page.keyboard.press('ArrowDown');const h=dd.locator('.is-hovering');if(await h.count()&&await h.first().innerText()===text){await page.keyboard.press('Enter');return}}throw Error('select '+text)}
async function review(action,reason='',success=true){await page.getByTestId('review-'+action).click();if(reason)await page.getByTestId('review-reason').fill(reason);const promise=page.waitForResponse(r=>r.url().endsWith('/review/'+action)&&r.request().method()==='POST');await page.getByTestId('review-confirm').click();const result=await(await promise).json();if(result.code!==(success?200:403)) console.log('review response',result.code,result.msg);check('Browser '+action+(success?'':' self denied'),result.code===(success?200:403));if(success)await expect(page.getByTestId('review-confirm')).toBeHidden();await settle()}
const fixture=(action)=>{const p=require('child_process').spawnSync('python3',[path.join(__dirname,'browser_fixture.py'),action,bid],{encoding:'utf8'});if(p.status!==0)throw Error('fixture '+action+': '+p.stderr);return JSON.parse(p.stdout)};
async function goBatch(){await page.goto(url+'/#/passport/batches?batch='+bid);await page.reload();await page.getByTestId('review-state').waitFor();await settle()}
async function doPublish(expected){await page.getByTestId('publish-open').click();await page.evaluate(()=>{window.__t9PublishingSeen=false;new MutationObserver(()=>{if(document.querySelector('[data-testid="publishing-state"]'))window.__t9PublishingSeen=true}).observe(document.body,{subtree:true,childList:true})});const response=page.waitForResponse(r=>r.url().endsWith('/publication')&&r.request().method()==='POST');await page.getByTestId('publish-confirm').click();const result=await(await response).json();check('Browser publish result '+expected,result.code===200&&result.data.record.publish_status===expected);await expect(page.getByTestId('publish-confirm')).toBeHidden();await settle();check('Browser displayed Publishing',await page.evaluate(()=>window.__t9PublishingSeen));return result.data}
try {await login('admin');const fixture=JSON.parse(fs.readFileSync(rt+'/test-artifacts/browser-fixtures.json'));bid=fixture.bid;await goBatch();await expect(page.getByTestId('review-state')).toHaveText('已发布');const body=await page.locator('body').innerText();check('No unresolved publication translation keys',!body.includes('passportReview.')&&!body.includes('passportPublish.'));await page.getByTestId('publication-panel').scrollIntoViewIfNeeded();await page.getByTestId('publication-panel').screenshot({path:rt+'/test-artifacts/publication-panel-final.png'});check('Final published panel remains V3',await page.getByTestId('published-current').innerText().then(s=>s.includes('V3')));check('Final UI no browser exceptions',errors.length===0)}catch(e){checks.push({name:'Final UI smoke',status:'FAIL',error:e.message});console.error(e);process.exitCode=1}finally{fs.writeFileSync(rt+'/test-artifacts/ui-smoke.json',JSON.stringify({checks,errors},null,2));await browser.close()}})();
