const {chromium,expect}=require('../go-admin-ui/node_modules/@playwright/test');const fs=require('fs'),path=require('path');const rt=path.resolve(__dirname,'../../runtime/t12-fix'),ui='http://127.0.0.1:19543',phase=process.argv[2]||'create',statefile=rt+'/test-artifacts/flow-state.json';
(async()=>{const checks=[],errors=[];const browser=await chromium.launch({executablePath:'/Users/lostar/Library/Caches/ms-playwright/chromium-1228/chrome-mac-arm64/Google Chrome for Testing.app/Contents/MacOS/Google Chrome for Testing',headless:true});const ctx=await browser.newContext({locale:'zh-CN',viewport:{width:1440,height:1100}}),page=await ctx.newPage();page.setDefaultTimeout(20000);const cred=JSON.parse(fs.readFileSync(rt+'/credentials.json')),users=JSON.parse(fs.readFileSync(rt+'/test-artifacts/users.json'));const role=['reject','approve'].includes(phase)?'reviewer':['publish','rollback','reconcile'].includes(phase)?'admin':'editor';let f=fs.existsSync(statefile)?JSON.parse(fs.readFileSync(statefile)):{};let auth;
page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error'&&!m.text().includes('Failed to load resource'))errors.push(m.text())});page.on('request',r=>{if(r.url().startsWith('http://127.0.0.1:18111')&&r.headers().authorization)auth=r.headers().authorization});
const check=(name,v=true)=>{checks.push({name,status:v?'PASS':'FAIL'});console.log(name,v);if(!v)throw Error(name)};
const settle=()=>page.waitForLoadState('networkidle');const save=()=>fs.writeFileSync(statefile,JSON.stringify(f,null,2));
async function select(el,text){await el.scrollIntoViewIfNeeded();await el.click();const dropdown=page.locator('.el-select-dropdown:visible');for(let n=0;n<110;n++){await page.keyboard.press('ArrowDown');const item=dropdown.locator('.is-hovering');if(await item.count()&&await item.first().innerText()===text){await page.keyboard.press('Enter');await expect(dropdown).toBeHidden();return}}throw Error('Missing option '+text)}
async function batch(){await page.goto(ui+'/#/passport/batches?batch='+f.batch_id);await page.reload();await expect(page.getByTestId('review-state')).toBeVisible();await settle()}
async function send(action){await page.getByTestId('review-'+action).click();if(action==='reject')await page.getByTestId('review-reason').fill('T12 TEST — please adjust packaging statement.');await page.getByTestId('review-confirm').click();await expect(page.locator('.el-dialog:visible')).toHaveCount(0);await settle()}
async function upload(panel,name){await panel.getByTestId('media-label').fill('T12 TEST '+name);await panel.getByTestId('media-public').check();const response=page.waitForResponse(r=>r.url().endsWith('/media')&&r.request().method()==='POST');await panel.getByTestId('media-upload').setInputFiles(rt+'/test-artifacts/'+name);const r=await(await response).json();check('Real Editor browser upload '+name,r.code===200);await expect(panel.locator('img')).toBeVisible();await settle()}
try{
await page.goto(ui+'/#/login');await page.locator('input[name=username]').fill(role==='admin'?cred.admin_username:users[role].username);await page.locator('input[name=password]').fill(role==='admin'?cred.admin_password:cred.test_password);for(const el of await page.locator('input').all()){if(!['username','password'].includes(await el.getAttribute('name'))&&await el.isVisible())await el.fill('0')}await page.locator('button.submit-btn').click();await page.waitForURL(u=>u.hash.includes('/dashboard'));check('Real login '+role);
if(phase==='create'){
 await page.goto(ui+'/#/passport/products');await page.getByTestId('create-product').click();await page.getByTestId('new-code').fill('PF-T12-TEST');await page.getByTestId('new-name').fill('Potato Flakes T12 Test');await page.getByTestId('confirm-create').click();await expect(page.getByTestId('selected-revision')).toContainText('R1');f.product_id=new URLSearchParams(page.url().split('?')[1]).get('product');save();check('Real UI creates Product R1')
}else if(phase==='upload-seal'){
 await page.goto(ui+'/#/passport/products?product='+f.product_id);await page.reload();await page.getByTestId('package_quantity').fill('25');await page.getByTestId('save-content').click();await settle();check('Editor maintains revision through UI');await upload(page.getByTestId('media-panel').first(),'main.png');await upload(page.getByTestId('section-row-gallery').getByTestId('media-panel'),'gallery.jpg');await page.screenshot({path:rt+'/test-artifacts/editor-upload.png',fullPage:true});
 await page.getByTestId('seal-revision').click();await page.locator('.el-message-box__btns .el-button--primary').click();await expect(page.getByTestId('selected-revision')).toContainText('已封版');await settle();check('Seal with actual images');check('Sealed upload controls absent',await page.getByTestId('media-upload').count()===0);await page.getByTestId('set-default').click();await expect(page.getByTestId('set-default')).toBeDisabled();check('Set R1 default')
}else if(phase==='r2'){
 await page.goto(ui+'/#/passport/products?product='+f.product_id);await page.reload();await page.getByTestId('clone-revision').click();await expect(page.getByTestId('selected-revision')).toContainText('R2');await settle();check('Real UI clones R1 with working media');const panel=page.getByTestId('media-panel').first();await panel.getByTestId('media-remove').click();await settle();await upload(panel,'replacement.png');await page.getByTestId('package_quantity').fill('30');await page.getByTestId('save-content').click();await settle();await page.getByTestId('translation-approved').check();await page.getByTestId('save-translation').click();await settle();await page.getByTestId('seal-revision').click();await page.locator('.el-message-box__btns .el-button--primary').click();await expect(page.getByTestId('selected-revision')).toContainText('已封版');await settle();await page.getByTestId('set-default').click();await expect(page.getByTestId('set-default')).toBeDisabled();check('R2 replacement image sealed and default');
}else if(phase==='v2-edit'){
 await batch();await page.getByTestId('override-package_quantity').locator('input:not([type=radio])').fill('22');await page.getByTestId('inspection-0').getByTestId('numeric_value').fill('2');await page.getByTestId('save-batch').click();await settle();await page.getByTestId('section-row-gallery').getByRole('button',{name:'覆盖',exact:true}).click();await page.getByTestId('section-caption').fill('T12 V2 replaced gallery');await page.getByTestId('section-save').click();await expect(page.locator('.el-dialog:visible')).toHaveCount(0);await settle();await upload(page.getByTestId('section-row-gallery').getByTestId('media-panel'),'replacement.png');check('V2 actual UI overrides gallery with newly uploaded image');
}else if(phase==='batch'){
 await page.goto(ui+'/#/passport/batches');await page.getByTestId('create-batch').click();await page.getByTestId('new-batch-product').click();await page.getByText('PF-T12-TEST',{exact:true}).last().click();await expect(page.getByTestId('new-batch-base')).toContainText('R1');await page.getByTestId('new-batch-code').fill('PF-T12-TEST-001');for(const [key,val]of [['production_date','2026-09-10'],['expiry_date','2027-09-10']]){const el=page.locator('.el-dialog:visible .el-date-editor input').nth(key==='production_date'?0:1);await el.fill(val);await el.press('Enter')};await page.getByTestId('confirm-batch-create').click();await expect(page.getByTestId('batch-heading')).toContainText('PF-T12-TEST-001');await settle();f.batch_id=new URLSearchParams(page.url().split('?')[1]).get('batch');save();
 const ov=page.getByTestId('override-package_quantity');await ov.locator('label').filter({hasText:'覆盖'}).click();await ov.locator('input:not([type=radio])').fill('20');await page.getByTestId('save-batch').click();await settle();check('Real Batch creation and20kg override');
}else if(phase==='inspections'){
 await batch();for(const [i,[code,name,unit]] of [['MOISTURE','Moisture','%'],['SUGAR','Reducing Sugar','%'],['VISCOSITY','Viscosity','mPa.s'],['DENSITY','Bulk Density','g/L'],['SPECKS','Black Specks','count']].entries()){
 await page.getByTestId('add-inspection').click();const card=page.getByTestId('inspection-'+i);await card.getByTestId('item_code').fill(code);await card.getByTestId('name').fill(name);await card.getByTestId('numeric_value').fill(String(i+1));await card.getByTestId('unit').fill(unit);await card.getByTestId('specification').fill('T12 TEST specification');await select(card.getByTestId('judgement'),'仅供参考');await card.getByText('允许作为公开候选',{exact:true}).click();}
 await page.getByTestId('save-batch').click();await settle();check('Five inspections entered through actual UI');
 await page.getByTestId('section-add').click();await page.getByTestId('section-key').fill('batch_statement');await page.getByTestId('section-title').fill('T12 Packaging Statement');await page.getByTestId('section-text').fill('T12 TEST packaging statement');await page.getByText('文字已确认（不是工作流审核）',{exact:true}).click();await page.getByText('公开意图',{exact:true}).click();await select(page.getByTestId('section-editor').locator('.el-select').nth(1),'就绪');await page.getByTestId('section-save').click();await expect(page.getByTestId('section-row-batch_statement')).toBeVisible();check('Actual UI creates ready public Batch-only section');
}else if(phase==='adjust'){
 await batch();await page.getByTestId('section-row-batch_statement').getByRole('button',{name:'修改',exact:true}).click();await page.getByTestId('section-text').fill('T12 TEST — packaging statement adjusted after rejection.');await page.getByTestId('section-save').click();await expect(page.locator('.el-dialog:visible')).toHaveCount(0);check('Editor adjusts rejected statement through UI');
}else if(phase==='submit'||phase==='resubmit'){
 await batch();await page.getByTestId('preview-working').click();await expect(page.getByTestId('private-passport').locator('img').first()).toBeVisible();await page.locator('.el-dialog__headerbtn').last().click();check('Working preview contains uploaded image');await send('submit');await expect(page.getByTestId('review-state')).toContainText('待审核');check('Real UI '+phase)
}else if(phase==='reject'||phase==='approve'){
 await page.goto(ui+'/#/passport/reviews?batch='+f.batch_id);await page.reload();await expect(page.getByTestId('review-state')).toBeVisible();await page.getByTestId('preview-review').click();await expect(page.getByTestId('private-passport').locator('img').first()).toBeVisible();await page.locator('.el-dialog__headerbtn').last().click();check('Reviewer frozen uploaded-image preview');await send(phase);check('Real UI '+phase)
}else if(phase==='publish'){
 await batch();await page.getByTestId('publish-open').click();await page.getByTestId('publish-confirm').click();await expect(page.getByTestId('published-current')).toBeVisible();check('Real Admin UI publishes approved image candidate')
}else if(phase==='rollback'){
 await batch();await select(page.getByTestId('compare-left'),'V1');await select(page.getByTestId('compare-right'),'V2');await page.getByTestId('compare-run').click();await expect(page.getByTestId('version-diff')).toBeVisible();check('Admin actual UI compares versions');await page.getByTestId('rollback-1').click();await page.getByTestId('history-reason').fill('T12 TEST — restore approved V1 content');await page.getByTestId('history-confirm').click();await expect(page.getByTestId('version-detail-3')).toBeVisible();check('Admin actual UI rollback creates V3');
}else if(phase==='reconcile'){
 const fault=JSON.parse(fs.readFileSync(rt+'/test-artifacts/db-failure-state.json'));f.batch_id=fault.batch_id;await batch();await page.getByTestId('history-reconcile').click();await page.getByTestId('history-reason').fill('T12 TEST — reconcile actual SQLite finalize failure');await page.getByTestId('history-confirm').click();await expect(page.getByTestId('history-health')).toContainText('一致');check('Admin actual UI reconciles original operation');
}else if(phase==='clone'){

 await batch();await page.getByTestId('clone-batch').click();await page.getByTestId('new-batch-code').fill('PF-T12-TEST-003');await page.getByTestId('confirm-batch-create').click();await expect(page.getByTestId('batch-heading')).toContainText('PF-T12-TEST-003');await expect(page.getByTestId('review-state')).toContainText('草稿');await expect(page.getByTestId('batch-base')).toContainText('R1');await settle();f.clone_id=new URLSearchParams(page.url().split('?')[1]).get('batch');save();check('Published source cloned through UI to new R1 Draft')
}
await page.screenshot({path:rt+'/test-artifacts/browser-'+phase+'.png',fullPage:true});check('No browser errors',errors.length===0);await page.locator('.avatar-wrapper').hover();await page.getByText('退出登录',{exact:true}).click();await page.locator('.el-message-box__btns .el-button--primary').click();await page.waitForURL(u=>u.hash.includes('/login'));check('Logout '+role)
}catch(e){checks.push({name:phase+' complete',status:'FAIL',error:e.message});console.error(e);process.exitCode=1;await page.screenshot({path:rt+'/test-artifacts/failure-'+phase+'.png',fullPage:true})}finally{fs.writeFileSync(rt+'/test-artifacts/browser-'+phase+'.json',JSON.stringify({checks,errors},null,2));await browser.close()}})();
